# WARNING - Generated by {fusen} from dev/dev_donor_focus.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compare donor profiles
#'
#' @description
#' Creates an overlaid bar chart to compare funding profiles of donors based on
#' a selected dimension (earmarking, region, or country). When only one donor 
#' is provided, a comparator is automatically added based on other donors.
#'
#' @param donor_names Character vector of donor names to compare (length 1 or more).
#' @param by One of "earmarking", "region", or "country". The dimension to compare.
#' @param avg_method If only one donor is supplied, how to compute the "others" comparator:
#'   - "mean_of_donors": Each donor counts equally, regardless of their total funding
#'   - "pooled": Donors are weighted by their share of total funding (larger donors have more influence)
#' @param display_mode Comparison mode:
#'   - "absolute": Compare absolute USD amounts (sum vs sum)
#'   - "relative": Compare percentage shares of total funding (profile vs average profile)
#' @param year Optional numeric/integer vector. Year(s) to filter on.
#' @param unhcr_region Optional character vector. Filter for UNHCR region(s).
#' @param programme_lab Optional character vector. Filter for programme name.
#' @param iati_identifier_ops Optional character vector. Filter for operation ID.
#' @param ctr_name Optional character vector. Filter for country name.
#' @param top_n Integer. The number of top categories to show when `by = "country"`.
#'
#' @return A ggplot object showing overlaid bars for comparison.
#'
#' @details
#' When `display_mode = "relative"` and a comparator is added:
#' - Selected donor: Percentage share of its own total funding
#' - Comparator: Average percentage share across other donors (using `avg_method`)
#' 
#' When `display_mode = "absolute"` and a comparator is added:
#' - Selected donor: Absolute USD amounts
#' - Comparator: Either:
#'   - With `avg_method = "mean_of_donors"`: Average donor size × average share
#'   - With `avg_method = "pooled"`: Summed totals across all other donors
#'
#' The chart uses visual cues to distinguish series:
#' - Wider transparent bars: Comparator
#' - Narrower solid bars: Selected donor(s)
#' - Colors represent categories within the dimension
#'
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#'
#' @export
#' @examples
#' # Compare Donor Profiles
#'
#' ## using mean
#' compare_donor_profiles(
#'   donor_names = "Private donors",
#'   by = "earmarking",
#'   year = 2025,
#'   avg_method = "mean_of_donors",
#'   display_mode = "absolute"
#' )
#' compare_donor_profiles(
#'   donor_names = "Private donors",
#'   by = "earmarking",
#'   year = 2025,
#'   avg_method = "mean_of_donors",
#'   display_mode = "relative"
#' )
#'
#' ## using pooled
#' compare_donor_profiles(
#'   donor_names = "Private donors",
#'   by = "earmarking",
#'   year = 2025,
#'   avg_method = "pooled",
#'   display_mode = "absolute"
#' )
#'
#'
#' compare_donor_profiles(
#'   donor_names = "Private donors",
#'   by = "earmarking",
#'   year = 2025,
#'   avg_method = "pooled",
#'   display_mode = "relative"
#' )
#'
#'
#' compare_donor_profiles(
#'   donor_names = "Private donors",
#'   by = "region",
#'   year = 2025,
#'   avg_method = "pooled",
#'   display_mode = "relative"
#' )
#'
#' compare_donor_profiles(
#'   donor_names = c("Private donors", 
#'  "Switzerland - Swiss Agency for Development and Cooperation (SDC)"), 
#'    by = "earmarking", 
#'  year = 2025, 
#'  ctr_name = "Brazil")
compare_donor_profiles <- function(donor_names,
                                   by = c("earmarking", "region", "country"),
                                   avg_method = c("mean_of_donors", "pooled"),
                                   display_mode = c("absolute", "relative"),
                                   year = NULL,
                                   unhcr_region = NULL,
                                   programme_lab = NULL,
                                   iati_identifier_ops = NULL,
                                   ctr_name = NULL,
                                   top_n = NULL) {

  by <- match.arg(by)
  avg_method <- match.arg(avg_method)
  display_mode <- match.arg(display_mode)

  # Avoid collisions with column names
  year_filter      <- year
  region_filter    <- unhcr_region
  programme_filter <- programme_lab
  ops_filter       <- iati_identifier_ops
  country_filter   <- ctr_name

  donor_names <- unique(donor_names)
  add_comparator <- length(donor_names) == 1

  # ---- 1) Load base data (ALL donors), then apply filters ----
  df_base <- iati::dataTransaction |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier") |>
    dplyr::filter(transaction_type_name == "Incoming Commitment")

  if (!is.null(year_filter)) {
    df_base <- df_base |> dplyr::filter(year %in% .env$year_filter)
  }
  if (!is.null(region_filter)) {
    df_base <- df_base |> dplyr::filter(unhcr_region %in% .env$region_filter)
  }
  if (!is.null(programme_filter)) {
    df_base <- df_base |> dplyr::filter(programme_lab %in% .env$programme_filter)
  }
  if (!is.null(ops_filter)) {
    df_base <- df_base |> dplyr::filter(iati_identifier_ops %in% .env$ops_filter)
  }
  if (!is.null(country_filter)) {
    df_base <- df_base |> dplyr::filter(ctr_name %in% .env$country_filter)
  }



  # ---- 2) Helper: build (donor, dimension, total_funding) ----
  build_profile <- function(df_in, by) {
    if (by == "earmarking") {
      df_in |>
        dplyr::filter(!is.na(earmarking_name)) |>
        dplyr::group_by(transaction_provider_org, earmarking_name) |>
        dplyr::summarise(
          total_funding = sum(transaction_value_USD, na.rm = TRUE),
          .groups = "drop"
        ) |>
        dplyr::rename(dimension = earmarking_name)
    } else if (by == "region") {
      df_in |>
        dplyr::group_by(transaction_provider_org, unhcr_region) |>
        dplyr::summarise(
          total_funding = sum(transaction_value_USD, na.rm = TRUE),
          .groups = "drop"
        ) |>
        dplyr::rename(dimension = unhcr_region)
    } else { # by == "country"
      df_in |>
        dplyr::filter(!is.na(ctr_name)) |>
        dplyr::group_by(transaction_provider_org, ctr_name) |>
        dplyr::summarise(
          total_funding = sum(transaction_value_USD, na.rm = TRUE),
          .groups = "drop"
        ) |>
        dplyr::rename(dimension = ctr_name)
    }
  }

  # ---- 3) Selected donors ----
  selected_df <- df_base |>
    dplyr::filter(transaction_provider_org %in% .env$donor_names)

  show_selected <- build_profile(selected_df, by)

  if (nrow(show_selected) == 0) {
    stop("No data found for the selected donor(s) under the specified filters.")
  }

  # ---- 4) Auto comparator if only one donor provided ----
  comparator_label <- NULL

  if (add_comparator) {
    focal <- donor_names[[1]]

    others_df <- df_base |>
      dplyr::filter(transaction_provider_org != .env$focal)

    show_others <- build_profile(others_df, by)

    if (nrow(show_others) == 0) {
      warning("No data found for 'other donors' under the specified filters. Showing only selected donor.")
      show_data <- show_selected
      add_comparator <- FALSE
      
    } else {

      if (avg_method == "mean_of_donors") {
        comparator_label <- "Average of other donors (equal weight)"
        
        # For relative display: average of donor-level percentage shares
        if (display_mode == "relative") {
          # Calculate percentage shares for each other donor
          others_totals <- show_others |>
            dplyr::group_by(transaction_provider_org) |>
            dplyr::summarise(donor_total = sum(total_funding, na.rm = TRUE), .groups = "drop")
          
        # First, get complete set of dimensions across all other donors
        all_dimensions <- unique(show_others$dimension)
        
        others_shares <- show_others |>
          dplyr::left_join(others_totals, by = "transaction_provider_org") |>
          # Calculate shares, treating missing as 0
          dplyr::mutate(
            share = dplyr::if_else(donor_total > 0, 
                                  total_funding / donor_total, 
                                  0)
          ) |>
          # Ensure we have all dimensions for each donor
          tidyr::complete(
            transaction_provider_org,
            dimension = all_dimensions,
            fill = list(share = 0, total_funding = 0, donor_total = 0)
          ) |>
          # Now average the shares (including 0s for missing dimensions)
          dplyr::group_by(dimension) |>
          dplyr::summarise(avg_share = mean(share, na.rm = FALSE), .groups = "drop")
          
          show_cmp <- others_shares |>
            dplyr::mutate(
              transaction_provider_org = comparator_label,
              total_funding = NA_real_,  # Not used for relative display
              share = avg_share
            ) |>
            dplyr::select(transaction_provider_org, dimension, total_funding, share)
          
      } else { # display_mode == "absolute"
        # Calculate actual average dollar amounts per donor
        # First, ensure we have all dimensions for each donor (treat missing as 0)
        all_dimensions <- unique(show_others$dimension)
        
        # Create complete data frame with all donor-dimension combinations
        complete_others <- show_others |>
          tidyr::complete(
            transaction_provider_org,
            dimension = all_dimensions,
            fill = list(total_funding = 0)
          )
        
        # Calculate average dollar amount per donor for each dimension
        avg_funding_by_dim <- complete_others |>
          dplyr::group_by(dimension) |>
          dplyr::summarise(
            avg_funding = mean(total_funding, na.rm = TRUE),
            .groups = "drop"
          )
        
        show_cmp <- avg_funding_by_dim |>
          dplyr::mutate(
            transaction_provider_org = comparator_label,
            total_funding = avg_funding,
            share = NA_real_  # Not used in absolute mode
          ) |>
          dplyr::select(transaction_provider_org, dimension, total_funding, share)
      }

      } else if (avg_method == "pooled") {
        comparator_label <- "Other donors (pooled)"
        
        # For both relative and absolute: use pooled totals
        pooled_totals <- show_others |>
          dplyr::group_by(dimension) |>
          dplyr::summarise(
            total_funding = sum(total_funding, na.rm = TRUE),
            .groups = "drop"
          )
        
        if (display_mode == "relative") {
          # Calculate percentage share of pooled total
          grand_total <- sum(pooled_totals$total_funding, na.rm = TRUE)
          show_cmp <- pooled_totals |>
            dplyr::mutate(
              transaction_provider_org = comparator_label,
              share = total_funding / grand_total
            ) |>
            dplyr::select(transaction_provider_org, dimension, total_funding, share)
        } else { # display_mode == "absolute"
          show_cmp <- pooled_totals |>
            dplyr::mutate(
              transaction_provider_org = comparator_label,
              share = NA_real_
            ) |>
            dplyr::select(transaction_provider_org, dimension, total_funding, share)
        }
      }

      # Calculate shares for selected donor
      selected_total <- sum(show_selected$total_funding, na.rm = TRUE)
      show_selected <- show_selected |>
        dplyr::mutate(
          share = total_funding / selected_total
        )
      
      show_data <- dplyr::bind_rows(show_selected, show_cmp)
    }

  } else {
    # Multiple donors - calculate shares if needed
    if (display_mode == "relative") {
      donor_totals <- show_selected |>
        dplyr::group_by(transaction_provider_org) |>
        dplyr::summarise(donor_total = sum(total_funding, na.rm = TRUE), .groups = "drop")
      
      show_data <- show_selected |>
        dplyr::left_join(donor_totals, by = "transaction_provider_org") |>
        dplyr::mutate(
          share = total_funding / donor_total
        ) |>
        dplyr::select(-donor_total)
    } else {
      show_data <- show_selected |>
        dplyr::mutate(share = NA_real_)
    }
  }

  # ---- 5) Apply top_n filter for country dimension ----
  if (by == "country" && !is.null(top_n) && is.numeric(top_n)) {
    # Keep top_n countries based on total funding across all shown donors
    top_countries <- show_data |>
      dplyr::group_by(dimension) |>
      dplyr::summarise(total = sum(total_funding, na.rm = TRUE), .groups = "drop") |>
      dplyr::arrange(dplyr::desc(total)) |>
      dplyr::slice(1:top_n) |>
      dplyr::pull(dimension)
    
    show_data <- show_data |>
      dplyr::filter(dimension %in% top_countries)
  }

  # ---- 6) Prepare data for overlaid bar chart ----
  # Create factor levels for dimension ordered by total funding
  dimension_levels <- show_data |>
    dplyr::group_by(dimension) |>
    dplyr::summarise(total = sum(total_funding, na.rm = TRUE), .groups = "drop") |>
    dplyr::arrange(dplyr::desc(total)) |>
    dplyr::pull(dimension)
  
  # Add type column for plotting
  
  if (is.null(comparator_label)) comparator_label <- NA_character_
  show_data <- show_data |>
    dplyr::mutate(
      dimension = factor(dimension, levels = dimension_levels),
      type = dplyr::case_when(
        transaction_provider_org %in% donor_names & add_comparator ~ "Selected Donor",
        transaction_provider_org %in% donor_names & !add_comparator ~ "Selected Donors",
        transaction_provider_org == comparator_label ~ "Comparator",
        TRUE ~ "Other"
      ),
      # Select value based on display mode
      value = if (display_mode == "absolute") total_funding else share
    )

  # ---- 7) Define colors and aesthetics ----
  # Use earmarking colors if by = "earmarking"
  if (by == "earmarking") {
    earmarking_colors <- c(
      "Tightly Earmarked" = "#C00000",
      "Earmarked" = "#FFC000",
      "Softly Earmarked" = "#0090BC",
      "Unearmarked" = "#36B3A1"
    )
    
    # Ensure colors match the dimension levels
    fill_colors <- earmarking_colors[dimension_levels[dimension_levels %in% names(earmarking_colors)]]
  } else {
    # For region and country, use a color palette
    fill_colors <- unhcrthemes::unhcr_pal(n = length(dimension_levels), "pal_unhcr")
    names(fill_colors) <- dimension_levels
  }

  # ---- 8) Create title ----
  # Build year string for title
  year_str <- if (!is.null(year_filter)) {
    if (length(year_filter) == 1) {
      paste("in", year_filter)
    } else {
      paste(range(year_filter), collapse = "-")
    }
  } else {
    "all years"
  }
  
  # Build title based on number of donors and display mode
  if (add_comparator) {
    if (display_mode == "relative") {
      title <- paste(donor_names[1], "vs average | ", year_str)
    } else {
      title <- paste(donor_names[1], "vs", tolower(gsub("\\(.*\\)", "", comparator_label)), ":", stringr::str_to_title(by), "profile", year_str)
    }
  } else if (length(donor_names) == 1) {
    title <- paste(donor_names[1], ":", stringr::str_to_title(by), "profile", year_str)
  } else {
    title <- paste("Comparison of", paste(donor_names, collapse = " & "), ":", stringr::str_to_title(by), "profile", year_str)
  }
  
  # Capitalize first letter of each word
  title <- stringr::str_to_title(title)

  # ---- 9) Build interpretation hints for caption ----
  caption_parts <- c(
    "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI)"
  )
  
  # Add interpretation hints
  if (add_comparator) {
    caption_parts <- c(caption_parts, 
                       "Wider transparent bars: Comparator | Narrower solid bars: Selected donor")
    
    # Add method hint
    method_desc <- if (avg_method == "mean_of_donors") {
      "Comparator: average of donor-level shares (each donor counts equally)"
    } else {
      "Comparator: pooled totals (donors weighted by funding share)"
    }
    caption_parts <- c(caption_parts, method_desc)
  }
  
  if (by == "earmarking") {
    caption_parts <- c(caption_parts, 
                       "Colors: Tightly Earmarked (red), Earmarked (orange), Softly Earmarked (blue), Unearmarked (green)")
  }
  
  if (display_mode == "relative") {
    caption_parts <- c(caption_parts, "Values: percentage share of total funding")
  } else {
    caption_parts <- c(caption_parts, "Values: absolute USD amounts")
  }
  
  # Add filter information if any filters applied
  filter_parts <- c()
  if (!is.null(region_filter) && length(region_filter) <= 3) {
    filter_parts <- c(filter_parts, paste("Region:", paste(region_filter, collapse = ", ")))
  }
  if (!is.null(country_filter) && length(country_filter) <= 3) {
    filter_parts <- c(filter_parts, paste("Country:", paste(country_filter, collapse = ", ")))
  }
  if (!is.null(programme_filter) && length(programme_filter) <= 2) {
    filter_parts <- c(filter_parts, paste("Programme:", paste(programme_filter, collapse = ", ")))
  }
  
  if (length(filter_parts) > 0) {
    caption_parts <- c(caption_parts, paste("Filters:", paste(filter_parts, collapse = "; ")))
  }
  
  caption <- paste(caption_parts, collapse = " | ")

  # ---- 10) Plot: Fully overlaid bar chart ----
  # Separate data for plotting
  plot_data <- show_data
  
  # Set bar widths and transparency
  bar_widths <- c("Selected Donor" = 0.6, "Selected Donors" = 0.6, "Comparator" = 0.8)
  bar_alphas <- c("Selected Donor" = 0.9, "Selected Donors" = 0.9, "Comparator" = 0.4)
  
  # Get unique types in correct order (Comparator first for layering)
  types_in_data <- unique(plot_data$type)
  # Ensure Comparator is drawn first (behind) if present
  if ("Comparator" %in% types_in_data) {
    plot_order <- c("Comparator", setdiff(types_in_data, "Comparator"))
  } else {
    plot_order <- types_in_data
  }
  
  # Create base plot
  p <- ggplot2::ggplot()
  
  # Add bars in correct order (comparator first, then selected donor)
  for (bar_type in plot_order) {
    type_data <- plot_data |> dplyr::filter(type == bar_type)
    
    if (nrow(type_data) > 0) {
      p <- p + ggplot2::geom_col(
        data = type_data,
        ggplot2::aes(x = dimension, y = value, fill = dimension),
        width = bar_widths[bar_type],
        alpha = bar_alphas[bar_type],
        position = "identity",  # Fully overlaid
        show.legend = FALSE      # Suppress individual bar legends
      )
    }
  }
  
  # Build the complete plot with all elements before applying any theme
  p <- p +
    ggplot2::coord_flip() +
    ggplot2::scale_fill_manual(values = fill_colors) +
    ggplot2::labs(
      title = title,
      x = NULL,
      y = if (display_mode == "absolute") "Total Funding (USD)" else "Share of Total Funding (%)",
      caption = caption
    )
  
  # Add appropriate y-axis scale
  if (display_mode == "absolute") {
    p <- p + ggplot2::scale_y_continuous(
      labels = scales::label_number(scale_cut = scales::cut_short_scale()),
      expand = ggplot2::expansion(mult = c(0, 0.1))
    )
  } else {
    p <- p + ggplot2::scale_y_continuous(
      labels = scales::label_percent(accuracy = 1),
      expand = ggplot2::expansion(mult = c(0, 0.05))
    )
  }
  
  p <- p + 
    unhcrthemes::theme_unhcr(grid = "X", axis = "Y", axis_title = "Y", 
                             font_size = 20, 
                             legend = FALSE) 

  
  return(p)
}
