# WARNING - Generated by {fusen} from dev/dev_template.Rmd: do not edit by hand # nolint: line_length_linter.

#' Generate Humanitarian Data Story from ggplot
#'
#' This function takes a ggplot2 object and generates a storytelling narrative.
#' It now uses a modular architecture (extract_structure,
#' profile_data, generate_description).
#'
#' @param plot A `ggplot` object.
#' @param max_tokens Max tokens for description.
#' @param provider LLM provider.
#' @param model LLM model.
#' @param max_tokens_short_desc Maximum token limit for the short desc 
#' - typically to be used for a chart subtitle
#' @param max_tokens_long_desc Maximum token limit for the short desc 
#' - typically to be used for a long narrative illustration
#'
#' @return A list containing `$short_desc` and `$long_desc`.
#' @export
#' @examples
#'
#' library(ggplot2) 
#' p <- ggplot(mtcars, aes(x = wt, y = mpg)) +
#'   geom_point() +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Vehicle Efficiency",
#'     subtitle = "Fuel consumption vs weight",
#'     caption = "Source: mtcars dataset"
#'   )
#'
#' # generate_plot_story(p, provider = "ollama", model = "deepseek-r1")
#'
#' story <- generate_plot_story(
#'   p,
#'   provider = "azure",
#'   model = "gpt-4.1-mini",
#'   max_tokens_short_desc = 30,
#'   max_tokens_long_desc= 500
#' )
#' # To use as subtitle:
#' p + ggplot2::labs(subtitle = story$short_desc)
generate_plot_story <- function(plot,
                                max_tokens = 300,
                                provider = NULL,
                                model = NULL,
                                max_tokens_short_desc = 30,
                                max_tokens_long_desc= 500) {

  if (is.null(plot) || !inherits(plot, "ggplot")) {
    return(list(
      short_desc = "Invalid input",
      long_desc = "Plot is NULL or not a ggplot object."
    ))
  }

  # Phase 1: Structure
  structure <- extract_structure(plot)

  # Phase 2: Profile
  stats <- profile_data(plot)

  # Phase 3: Semantic Generation
  description <- generate_description(
    structure,
    stats,
    provider,
    model,
    max_tokens_short_desc,
    max_tokens_long_desc
  )

  description
}
