# WARNING - Generated by {fusen} from dev/flat_dev_report.Rmd: do not edit by hand # nolint: line_length_linter.

#' Generate Quarto HTML / PDF Country Factsheets in Batch
#'
#' This function renders the 'Country_Factsheet' Quarto template for a list of
#' countries, generating a report file for each.
#'
#' @param type either donor recipient or destination.
#' @param name name of  donor recipient or destination if NULL batch process them
#' @param top_n Top number of report to batch process based on total amount
#'
#' @importFrom dplyr filter select pull
#' @importFrom quarto quarto_render
#' @importFrom here here
#'
#' @return links to genrated reports.
#'
#' @export
#' @examples
#'
#' # linkdonor <- generate_report(type = "donor", top_n = 20)
#' # dput(linkdonor)
#' linkdonor <-   c("[Profile Report for donor: United States of America (Government of)](../reports/iatiAnalysis-donor-united-states-of-america-government-of.html)", 
#' "[Profile Report for donor: Mastercard Foundation](../reports/iatiAnalysis-donor-mastercard-foundation.html)", 
#' "[Profile Report for donor: Private donors](../reports/iatiAnalysis-donor-private-donors.html)", 
#' "[Profile Report for donor: European Commission - Humanitarian Aid & Civil Protection](../reports/iatiAnalysis-donor-european-commission-humanitarian-aid-civil-protection.html)", 
#' "[Profile Report for donor: Denmark - Ministry of Foreign Affairs, Danida](../reports/iatiAnalysis-donor-denmark-ministry-of-foreign-affairs-danida.html)", 
#' "[Profile Report for donor: European Commission - Service for Foreign Policy Instruments](../reports/iatiAnalysis-donor-european-commission-service-for-foreign-policy-instruments.html)", 
#' "[Profile Report for donor: European Commission - Neighbourhood and Enlargement Negotiations](../reports/iatiAnalysis-donor-european-commission-neighbourhood-and-enlargement-negotiations.html)", 
#' "[Profile Report for donor: Norad - Norwegian Agency for Development Cooperation](../reports/iatiAnalysis-donor-norad-norwegian-agency-for-development-cooperation.html)", 
#' "[Profile Report for donor: Netherlands - Ministry of Foreign Affairs](../reports/iatiAnalysis-donor-netherlands-ministry-of-foreign-affairs.html)", 
#' "[Profile Report for donor: Germany - Federal Foreign Office](../reports/iatiAnalysis-donor-germany-federal-foreign-office.html)", 
#' "[Profile Report for donor: Ministry of Foreign Affairs of  Japan](../reports/iatiAnalysis-donor-ministry-of-foreign-affairs-of-japan.html)", 
#' "[Profile Report for donor: UK - Foreign, Commonwealth and Development Office](../reports/iatiAnalysis-donor-uk-foreign-commonwealth-and-development-office.html)", 
#' "[Profile Report for donor: Sweden, through Swedish International Development Cooperation Agency (Sida)](../reports/iatiAnalysis-donor-sweden-through-swedish-international-development-cooperation-agency-sida.html)", 
#' "[Profile Report for donor: Canada - Global Affairs Canada | Affaires mondiales Canada](../reports/iatiAnalysis-donor-canada-global-affairs-canada-affaires-mondiales-canada.html)", 
#' "[Profile Report for donor: Switzerland - Swiss Agency for Development and Cooperation (SDC)](../reports/iatiAnalysis-donor-switzerland-swiss-agency-for-development-and-cooperation-sdc.html)", 
#' "[Profile Report for donor: España con ACNUR](../reports/iatiAnalysis-donor-espana-con-acnur.html)", 
#' "[Profile Report for donor: Republic of Korea](../reports/iatiAnalysis-donor-republic-of-korea.html)", 
#' "[Profile Report for donor: Italy (Government of)](../reports/iatiAnalysis-donor-italy-government-of.html)", 
#' "[Profile Report for donor: Japan for UNHCR](../reports/iatiAnalysis-donor-japan-for-unhcr.html)", 
#' "[Profile Report for donor: Ireland - Department of Foreign Affairs](../reports/iatiAnalysis-donor-ireland-department-of-foreign-affairs.html)"
#' )
#'
#' # linkoperation <- generate_report(type = "operation")
#' # dput(linkoperation)
#' # linkoperation <- c()
#'
#' ##  Operations 
#'
#' ##`r paste0("- ", linkoperation, collapse = "\n")`
#'
generate_report <- function(type="donor",
                            name=NULL,
                            top_n = 20) {
  
  template_path = system.file(paste0("_extension/", type,"/template.qmd"), 
                                package = "iati")
  ## Create the outfolder if it does not exist
  folder <- "docs/reports"
  output_dir <- here::here(folder)
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
    message("Created output directory: ", output_dir)
  }
  
  # Ensure template exists
  if (!file.exists(template_path)) {
    stop("Quarto template not found at: ", template_path, 
         ". Please check the template_path argument.")
  }
  
  # --- Loop through each country for batch rendering ---
  if ( is.null(name)){
    if(type == "donor") {
      name <- iati::dataTransaction |> 
             dplyr::left_join(iati::dataActivity, by= c("iati_identifier")) |> 
            dplyr::filter(  year == 2025 & 
                            transaction_type_name == "Incoming Commitment") |>
            dplyr::group_by(year, transaction_provider_org) |>
            dplyr::summarise( transaction_value_USD = sum(transaction_value_USD , na.rm = TRUE)) |>
            dplyr::arrange( desc(transaction_value_USD)) |>
            dplyr::slice_head(n =20) |>
            dplyr::pull( transaction_provider_org)
    }
  

    
    
    if(type == "operation") {
      name <-  data |>
                sort()|>
                unique()
    }
  } 
  links <- c()
  for ( this in name) {
    # this <- name
    # 2. Define Output Filename and Path
    thisslug <- slugify(this)
    output_filename <- paste0('iatiAnalysis-', type, '-', thisslug , '.html')
    output_filepath <- here::here(folder,output_filename )

    # 3. Render the Quarto document
    tryCatch({
      quarto::quarto_render(
        input = template_path,
        output_file = output_filename,
        # Pass parameters to the YAML header and R code chunks
        execute_params = list(name = this )
      )
      # Move the file
     file.rename(from = here::here( system.file(paste0("_extension/", type),
                                package = "iati"),
                                output_filename ),
                 to = output_filepath)
      message("Successfully generated: ", output_filename)
    # Link
      link <- paste0( "[Profile Report for ",
                      type,": ", 
                      this, "](../reports/",
                      output_filename,")")
    }, error = function(e) {
      warning("Failed to render report for ", this, ": ", e$message)
    })
    # links
    links <- c(links, link)
  }
  
  return(links)
}
