# WARNING - Generated by {fusen} from dev/dev_data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' Safely get a value from an XML node
#' @noRd
get_xml_value <- function(node, xpath, attr = NULL, pos = 1L) {
  if (!inherits(node, "xml_node")) {
    return(NA_character_)
  }
  found_nodes <- xml2::xml_find_all(node, xpath)
  if (length(found_nodes) < pos) {
    return(NA_character_)
  }
  target_node <- found_nodes[[pos]]
  if (!is.null(attr)) {
    value <- xml2::xml_attr(target_node, attr)
  } else {
    value <- xml2::xml_text(target_node)
  }
  if (is.na(value) || value == "") {
    return(NA_character_)
  }
  value
}
