# WARNING - Generated by {fusen} from dev/dev_data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' @noRd
iati_document_link <- function(xml_iati, verbose = TRUE) {
    log_debug("Extracting document links...", verbose = verbose)
  nodes <- xml2::xml_find_all(xml_iati, './/iati-activity/document-link')
    log_debug("Found ", length(nodes), " document link nodes.", verbose = verbose)
  df <- purrr::map_dfr(nodes, function(node) {
    tibble::tibble(
      iati_identifier = get_xml_value(node, "ancestor::iati-activity/iati-identifier"),
      document_url = get_xml_value(node, ".", attr = "url"),
      document_format = get_xml_value(node, ".", attr = "format"),
      document_title =  get_xml_value(node, "title/narrative"),
      document_category_code = get_xml_value(node, "category", attr = "code"),
      document_language_code = get_xml_value(node, "language", attr = "code"),
      document_date = get_xml_value(node, "document-date", attr = "iso-date")
    )
  })
    log_debug("Finished extracting document links. Rows: ", nrow(df), verbose = verbose)
    return(df)
}
