# WARNING - Generated by {fusen} from dev/dev_data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' @noRd
iati_location <- function(xml_iati, verbose = TRUE) {
    log_debug("Extracting locations...", verbose = verbose)
  nodes <- xml2::xml_find_all(xml_iati, './/iati-activity/location')
    log_debug("Found ", length(nodes), " location nodes.", verbose = verbose)
  df <- purrr::map_dfr(nodes, function(node) {
    point_text <- get_xml_value(node, "point/pos")
    lat <- if (!is.na(point_text)) strsplit(point_text, " ")[[1]][1] else NA_character_
    long <- if (!is.na(point_text)) strsplit(point_text, " ")[[1]][2] else NA_character_
    
    tibble::tibble(
      iati_identifier = get_xml_value(node, "ancestor::iati-activity/iati-identifier"),
      location_ref = get_xml_value(node, ".", attr = "ref"),
      location_reach_code = get_xml_value(node, "location-reach", attr = "code"),
      location_id_vocabulary = get_xml_value(node, "location-id", attr = "vocabulary"),
      location_id_code = get_xml_value(node, "location-id", attr = "code"),
      location_name = get_xml_value(node, "name/narrative"),
      location_type = get_xml_value(node, "description/narrative"),
      location_activity_descr = get_xml_value(node, "activity-description/narrative"),
      location_adm_vocabulary = get_xml_value(node, "administrative", attr = "vocabulary"),
      location_adm_level = get_xml_value(node, "administrative", attr = "level"),
      location_adm_code = get_xml_value(node, "administrative", attr = "code"),
      location_lat = lat,
      location_long = long,
      location_exactness_code = get_xml_value(node, "exactness", attr = "code"),
      location_class_code = get_xml_value(node, "location-class", attr = "code"),
      location_feature_designation_code = get_xml_value(node, "feature-designation", attr = "code")
    )
  })
    log_debug("Finished extracting locations. Rows: ", nrow(df), verbose = verbose)
    return(df)
}
