# WARNING - Generated by {fusen} from dev/Data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' iati_reshape
#' 
#' Take anxml file and creates all the decomposed xls file out o it..
#' 
#' @param xml_iati xml_iati
#' @param folder_name folder_name within project
#' 
#' @import fs
#' @import xml2
#' @import purrr
#' @import future
#' 
#' @export
#' @examples
#' #iati_reshape(
#' # iati_file_url = 'https://files.unhcr.org/en/reporting/unhcr-activities-2022.xml' , 
#' # folder_name = "data-raw")
#'
#' #iati_reshape( iati_file_url = 'https://files.unhcr.org/en/reporting/unhcr-activities-2022.xml' ,   folder_name = "data-raw")
#' #iati_reshape( iati_file_url = 'https://files.unhcr.org/en/reporting/unhcr-activities-2023.xml' ,   folder_name = "data-raw")
#' #iati_reshape( iati_file_url = 'https://files.unhcr.org/en/reporting/unhcr-activities-2024.xml' ,   folder_name = "data-raw")
#' #iati_reshape( iati_file_url = 'https://files.unhcr.org/en/reporting/unhcr-activities-2025.xml' ,   folder_name = "data-raw")
#' #iati_reshape( iati_file_url = 'https://files.unhcr.org/en/reporting/unhcr-activities-2026.xml' ,   folder_name = "data-raw")
iati_reshape <- function( iati_file_url = 'https://files.unhcr.org/en/reporting/unhcr-activities-2026.xml' , 
                         folder_name = "data-raw"){
  
  # A workflow to pull and tidy IATI data for UNHCR - https://reporting.unhcr.org/iati
  t1 <- Sys.time() 

  #fs::dir_ls("inst/source/", recurse = TRUE, type = "file") |> purrr::walk(source)

# create folder -----------------------------------------------------------
#folder_name = "data-raw-unhcr"
fs::dir_create(folder_name) 

# read data ---------------------------------------------------------------
iati_file <- fs::file_temp()

# https://files.unhcr.org/en/reporting/unhcr-activities-2020.xml
# https://files.unhcr.org/en/reporting/unhcr-activities-2023.xml

utils::download.file( iati_file_url, 
              iati_file, 
              quiet = TRUE)

# run each one of the tasks ------------
future::plan(future::multisession)
# list tasks --------------------------------------------------------------
list(
  iati_activity = iati_activity,
  iati_budget = iati_budget,
  iati_default_aid_type = iati_default_aid_type,
  iati_document_link = iati_document_link,
  iati_humanitarian_scope = iati_humanitarian_scope,
  iati_location = iati_location,
  iati_participating_org = iati_participating_org,
  iati_related_activity = iati_related_activity,
  iati_result = iati_result,
  iati_sector = iati_sector,
  iati_transaction = iati_transaction
)  |>
  
  # The furrr::future_map function is used to apply the xml2::read_xml function to each element of the iati_extractors object in parallel.
  # The ~rlang::exec(., xml2::read_xml(iati_file)) syntax is a shorthand for defining an anonymous function that takes one argument and applies the xml2::read_xml function to it.
  # The . is a placeholder for the argument, which is the current element of the iati_extractors object.
  # The iati_file variable is assumed to contain the path to the IATI XML file.
  furrr::future_map( ~ rlang::exec(., xml2::read_xml(iati_file))) |>
 # The iwalk function is then used to assign each element of the resulting list to a new variable in the global environment. 
  # The .y argument specifies the name of the new variable, and the .x argument specifies the value to be assigned.

# The envir = .GlobalEnv argument specifies that the new variable should be created in the global environment.

  purrr::iwalk( ~ assign(.y, .x, envir = .GlobalEnv))

Sys.time() - t1

# rm(iati_extractors,
#    iati_file,
#    t1,
#    xml_attr_by_name,
#    xml_child_attr_by_name,
#    xml_text_by_lang,
#    xml_text_by_name)

    
}
