# WARNING - Generated by {fusen} from dev/dev_data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' @noRd
iati_participating_org <- function(xml_iati, verbose = TRUE) {
    log_debug("Extracting participating organizations...", verbose = verbose)
  nodes <- xml2::xml_find_all(xml_iati, './/iati-activity/participating-org')
    log_debug("Found ", length(nodes), " participating organization nodes.", verbose = verbose)
  df <- purrr::map_dfr(nodes, function(node) {
    tibble::tibble(
      iati_identifier = get_xml_value(node, "ancestor::iati-activity/iati-identifier"),
      participating_org_eng = get_xml_value(node, "narrative"),
      participating_org_ref = get_xml_value(node, ".", attr = "ref"),
      participating_org_type = get_xml_value(node, ".", attr = "type"),
      participating_org_role = get_xml_value(node, ".", attr = "role"),
      participating_org_activity_id = get_xml_value(node, ".", attr = "activity-id"), 
      participating_org_crs_channel_code = get_xml_value(node, ".", attr = "crs-channel-code")
    )
  })
    log_debug("Finished extracting participating organizations. Rows: ", nrow(df), verbose = verbose)
    return(df)
}
