# WARNING - Generated by {fusen} from dev/dev_data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' @noRd
iati_humanitarian_scope <- function(xml_iati, verbose = TRUE) {
    log_debug("Extracting humanitarian scopes...", verbose = verbose)
  nodes <- xml2::xml_find_all(xml_iati, './/iati-activity/humanitarian-scope')
    log_debug("Found ", length(nodes), " humanitarian scope nodes.", verbose = verbose)
  df <- purrr::map_dfr(nodes, function(node) {
    tibble::tibble(
      iati_identifier = get_xml_value(node, "ancestor::iati-activity/iati-identifier"),
      humanitarian_scope_type = get_xml_value(node, ".", attr = "type"),
      humanitarian_scope_vocabulary = get_xml_value(node, ".", attr = "vocabulary"),
      humanitarian_scope_vocabulary_uri = get_xml_value(node, ".", attr = "vocabulary-uri"),
      humanitarian_scope_code = get_xml_value(node, ".", attr = "code"),
      humanitarian_scope_desc_eng = get_xml_value(node, "narrative[not(@xml:lang) or @xml:lang='en']"),
      humanitarian_scope_desc_fr = get_xml_value(node, "narrative[@xml:lang='fr']")
    )
  })
    log_debug("Finished extracting humanitarian scopes. Rows: ", nrow(df), verbose = verbose)
    return(df)
}
