# WARNING - Generated by {fusen} from dev/dev_data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' @noRd
iati_related_activity <- function(xml_iati, verbose = TRUE) {
    log_debug("Extracting related activities...", verbose = verbose)
  nodes <- xml2::xml_find_all(xml_iati, './/iati-activity/related-activity')
    log_debug("Found ", length(nodes), " related activity nodes.", verbose = verbose)
  df <- purrr::map_dfr(nodes, function(node) {
    tibble::tibble(
      iati_identifier = get_xml_value(node, "ancestor::iati-activity/iati-identifier"),
      related_activity_ref = get_xml_value(node, ".", attr = "ref"),
      related_activity_type = get_xml_value(node, ".", attr = "type")
    )
  })
  log_debug("Finished extracting related activities. Rows: ", nrow(df), verbose = verbose)
  return(df)
}
