# WARNING - Generated by {fusen} from dev/dev_data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' @noRd
iati_default_aid_type <- function(xml_iati, verbose = TRUE) {
    log_debug("Extracting default aid types...", verbose = verbose)
  nodes <- xml2::xml_find_all(xml_iati, './/iati-activity/default-aid-type')
    log_debug("Found ", length(nodes), " default aid type nodes.", verbose = verbose)
  df <- purrr::map_dfr(nodes, function(node) {
    tibble::tibble(
      iati_identifier = get_xml_value(node, "ancestor::iati-activity/iati-identifier"),
      default_aid_type_code = get_xml_value(node, ".", attr = "code"),
      default_aid_type_vocabulary = get_xml_value(node, ".", attr = "vocabulary")
    )
  })
    log_debug("Finished extracting default aid types. Rows: ", nrow(df), verbose = verbose)
    return(df)
}
