# WARNING - Generated by {fusen} from dev/dev_data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' @noRd
iati_policy_marker <- function(xml_iati, verbose = TRUE) {
  log_debug("Extracting policy markers...", verbose = verbose)
  nodes <- xml2::xml_find_all(xml_iati, './/iati-activity/policy-marker')
  log_debug("Found ", length(nodes), " policy marker nodes.", verbose = verbose)
  df <- purrr::map_dfr(nodes, function(node) {
    tibble::tibble(
      iati_identifier = get_xml_value(node, "ancestor::iati-activity/iati-identifier"),
      policy_marker_vocabulary = get_xml_value(node, ".", attr = "vocabulary"),
      policy_marker_code = get_xml_value(node, ".", attr = "code"),
      policy_marker_significance = get_xml_value(node, ".", attr = "significance"),
      policy_marker_uri = get_xml_value(node, ".", attr = "policy-marker-uri"),
      policy_marker_desc = get_xml_value(node, "narrative")
    )
  })
  log_debug("Finished extracting policy markers. Rows: ", nrow(df), verbose = verbose)
  return(df)
}

#' @noRd
iati_sector <- function(xml_iati, verbose = TRUE) {
  log_debug("Extracting sectors...", verbose = verbose)
  sector_nodes <- xml2::xml_find_all(xml_iati, './/iati-activity/sector')
  log_debug("Found ", length(sector_nodes), " sector nodes.", verbose = verbose)
  df <- purrr::map_dfr(sector_nodes, function(node) {
    tibble::tibble(
      iati_identifier = get_xml_value(node, "ancestor::iati-activity/iati-identifier"),
      sector_vocabulary = get_xml_value(node, ".", attr = "vocabulary"),
      sector_vocabulary_uri = get_xml_value(node, ".", attr = "vocabulary-uri"),
      sector_code = get_xml_value(node, ".", attr = "code"),
      sector_pct = get_xml_value(node, ".", attr = "percentage"),
      sector_desc = get_xml_value(node, "narrative")
    )
  })
  log_debug("Finished extracting sectors. Rows: ", nrow(df), verbose = verbose)
  return(df)
}

#' @noRd
iati_tag <- function(xml_iati, verbose = TRUE) {
  log_debug("Extracting tags...", verbose = verbose)
  nodes <- xml2::xml_find_all(xml_iati, './/iati-activity/tag')
  log_debug("Found ", length(nodes), " tag nodes.", verbose = verbose)
  df <- purrr::map_dfr(nodes, function(node) {
    tibble::tibble(
      iati_identifier = get_xml_value(node, "ancestor::iati-activity/iati-identifier"),
      tag_vocabulary = get_xml_value(node, ".", attr = "vocabulary"),
      tag_code = get_xml_value(node, ".", attr = "code"),
      tag_desc = get_xml_value(node, "narrative")
    )
  })
  log_debug("Finished extracting tags. Rows: ", nrow(df), verbose = verbose)
  return(df)
}

#' @noRd
iati_transaction <- function(xml_iati, verbose = TRUE) {
  log_debug("Extracting transactions...", verbose = verbose)
  transaction_nodes <- xml2::xml_find_all(xml_iati, './/iati-activity/transaction')
  log_debug("Found ", length(transaction_nodes), " transaction nodes.", verbose = verbose)
  df <- purrr::map_dfr(transaction_nodes, function(node) {
    tibble::tibble(
      iati_identifier = get_xml_value(node, "ancestor::iati-activity/iati-identifier"),
      transaction_ref = get_xml_value(node, ".", attr = "ref"),
      transaction_humanitarian = get_xml_value(node, ".", attr = "humanitarian"),
      transaction_type_code = get_xml_value(node, "transaction-type", attr = "code"),
      transaction_date = get_xml_value(node, "transaction-date", attr = "iso-date"),
      transaction_value_currency = get_xml_value(node, "value", attr = "currency"),
      transaction_value_date = get_xml_value(node, "value", attr = "value-date"),
      transaction_value = get_xml_value(node, "value"),
      transaction_value_USD = get_xml_value(node, "unhcr:value-USD"),
      transaction_description = get_xml_value(node, "description/narrative"),
      transaction_provider_org_type = get_xml_value(node, "provider-org", attr = "type"),
      transaction_provider_org_ref = get_xml_value(node, "provider-org", attr = "ref"),
      transaction_provider_org = get_xml_value(node, "provider-org/narrative"),
      transaction_aid_type_code_1 = get_xml_value(node, "aid-type", attr = "code", pos = 1),
      transaction_aid_type_vocabulary_1 = get_xml_value(node, "aid-type", attr = "vocabulary", pos = 1),
      transaction_aid_type_code_2 = get_xml_value(node, "aid-type", attr = "code", pos = 2),
      transaction_aid_type_vocabulary_2 = get_xml_value(node, "aid-type", attr = "vocabulary", pos = 2)
    )
  })
  log_debug("Finished extracting transactions. Rows: ", nrow(df), verbose = verbose)
  return(df)
}
