# WARNING - Generated by {fusen} from dev/dev_data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' @noRd
iati_activity <- function(xml_iati, verbose = TRUE) {
    log_debug("Extracting activities...", verbose = verbose)
  nodes <- xml2::xml_find_all(xml_iati, './/iati-activity')
    log_debug("Found ", length(nodes), " activity nodes.", verbose = verbose)
  df <- purrr::map_dfr(nodes, function(node) {
    tibble::tibble(
      iati_identifier = get_xml_value(node, "iati-identifier"),
      reporting_org = get_xml_value(node, "reporting-org/narrative"),
      reporting_org_ref = get_xml_value(node, "reporting-org", attr = "ref"),
      reporting_org_type = get_xml_value(node, "reporting-org", attr = "type"),
      reporting_org_secondary_reporter = get_xml_value(node, "reporting-org", attr = "secondary-reporter"),
      
      title_eng = get_xml_value(node, "title/narrative[not(@xml:lang) or @xml:lang='en']"),
      title_fr = get_xml_value(node, "title/narrative[@xml:lang='fr']"),
      
      description_type_1 = get_xml_value(node, "description", attr = "type", pos = 1),
      description_eng_1 = get_xml_value(xml2::xml_find_all(node, "description")[[1]], "narrative[not(@xml:lang) or @xml:lang='en']"),
      description_fr_1 = get_xml_value(xml2::xml_find_all(node, "description")[[1]], "narrative[@xml:lang='fr']"),
      
      description_type_2 = get_xml_value(node, "description", attr = "type", pos = 2),
      description_eng_2 = get_xml_value(xml2::xml_find_all(node, "description")[[2]], "narrative[not(@xml:lang) or @xml:lang='en']"),
      description_fr_2 = get_xml_value(xml2::xml_find_all(node, "description")[[2]], "narrative[@xml:lang='fr']"),
      
      activity_status_code = get_xml_value(node, "activity-status", attr = "code"),
      
      activity_date_1 = get_xml_value(node, "activity-date", attr = "iso-date", pos = 1),
      activity_date_type_1 = get_xml_value(node, "activity-date", attr = "type", pos = 1),
      activity_date_2 = get_xml_value(node, "activity-date", attr = "iso-date", pos = 2),
      activity_date_type_2 = get_xml_value(node, "activity-date", attr = "type", pos = 2),
      activity_date_3 = get_xml_value(node, "activity-date", attr = "iso-date", pos = 3),
      activity_date_type_3 = get_xml_value(node, "activity-date", attr = "type", pos = 3),
      activity_date_4 = get_xml_value(node, "activity-date", attr = "iso-date", pos = 4),
      activity_date_type_4 = get_xml_value(node, "activity-date", attr = "type", pos = 4),
      
      contact_info_type = get_xml_value(node, "contact-info", attr = "type"),
      contact_info_org = get_xml_value(node, "contact-info/organisation/narrative"),
      contact_info_email = get_xml_value(node, "contact-info/email"),
      contact_info_website = get_xml_value(node, "contact-info/website"),
      
      activity_scope_code = get_xml_value(node, "activity-scope", attr = "code"),
      
      recipient_country_code = get_xml_value(node, "recipient-country", attr = "code"),
      recipient_country_pct = get_xml_value(node, "recipient-country", attr = "percentage"),
      recipient_country = get_xml_value(node, "recipient-country/narrative"),
      
      recipient_region_code = get_xml_value(node, "recipient-region", attr = "code"),
      recipient_region_vocabulary = get_xml_value(node, "recipient-region", attr = "vocabulary"),
      recipient_region = get_xml_value(node, "recipient-region/narrative"),
      
      collaboration_type_code = get_xml_value(node, "collaboration-type", attr = "code"),
      default_flow_type_code = get_xml_value(node, "default-flow-type", attr = "code"),
      default_finance_type_code = get_xml_value(node, "default-finance-type", attr = "code"),
      default_tied_status_code = get_xml_value(node, "default-tied-status", attr = "code"),
      capital_spend = get_xml_value(node, "capital-spend", attr = "percentage")
    )
  })
    log_debug("Finished extracting activities. Rows: ", nrow(df), verbose = verbose)
    return(df)
}
