# WARNING - Generated by {fusen} from dev/dev_data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' @noRd
iati_budget <- function(xml_iati, verbose = TRUE) {
    log_debug("Extracting budgets...", verbose = verbose)
  nodes <- xml2::xml_find_all(xml_iati, './/iati-activity/budget')
    log_debug("Found ", length(nodes), " budget nodes.", verbose = verbose)
  df <- furrr::future_map_dfr(nodes, function(node) {
    tibble::tibble(
      iati_identifier = get_xml_value(node, "ancestor::iati-activity/iati-identifier"),
      budget_type = get_xml_value(node, ".", attr = "type"),
      budget_status = get_xml_value(node, ".", attr = "status"),
      budget_period_start = get_xml_value(node, "period-start", attr = "iso-date"),
      budget_period_end = get_xml_value(node, "period-end", attr = "iso-date"),
      budget_currency = get_xml_value(node, "value", attr = "currency"),
      budget_value_date = get_xml_value(node, "value", attr = "value-date"),
      budget_value = get_xml_value(node, "value")
    )
  }, .progress = TRUE)
    log_debug("Finished extracting budgets. Rows: ", nrow(df), verbose = verbose)
    return(df)
}
