# WARNING - Generated by {fusen} from dev/dev_data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' Log a debug message
#' @description A simple logger that prepends a timestamp and [DEBUG] prefix.
#' @param ... The message parts to be passed to `message()`.
#' @param verbose A boolean to control if the message is printed.
#' @noRd
log_debug <- function(..., verbose = TRUE) {
  if (verbose) {
    message(Sys.time(), " [DEBUG] ", ...)
  }
}
