# WARNING - Generated by {fusen} from dev/dev_donor_focus.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot donor regional and programme focus as a treemap
#'
#' @description
#' This function generates a treemap visualization showing a donor's funding
#' allocation across UNHCR regions and within those regions, by programme.
#' The size of each treemap tile can represent either the absolute funding
#' amount or the share of the donor's total funding for that programme within a region.
#'
#' @param donor_name Character. The name of the donor to analyze.
#' @param year Numeric or integer vector. Year(s) to filter the data.
#' @param measure_type Character. One of "total_amount_usd" (default) or "share".
#'   - "total_amount_usd": Tile size represents the absolute USD amount.
#'   - "share": Tile size represents the share of the donor's total funding
#'     that goes to a specific programme within a specific UNHCR region.
#' @param label_font_size Numeric. Base font size for treemap labels.
#'
#' @return A ggplot object representing the treemap.
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import treemapify
#' @import unhcrthemes
#'
#' @export
#' @examples
#' # Example usage:
#' plot_donor_regional_focus_treemap(
#'   donor_name = "Private donors",
#'   year =  2025 
#' )
#'  
plot_donor_regional_focus_treemap <- function(donor_name,
                                              year = NULL ) {

 
  # ---- 1) Get IATI data ----
  df <- iati::dataTransaction |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier") |>
    dplyr::filter(
      transaction_type_name == "Incoming Commitment"
    )

  # Filtering by year
  if (!is.null(year)) {
    df <- df |> dplyr::filter(year %in% .env$year)
  }

  if (nrow(df) == 0) {
    stop("No data found for the selected donor and year(s).")
  }
  
  # Ensure necessary columns are not NA
  df <- df |>
    dplyr::filter(!is.na(unhcr_region), !is.na(activity_name), !is.na(transaction_value_USD))

  if (nrow(df) == 0) {
    stop("No data remaining after filtering out NA values for region, programme, or funding.")
  }

  # ---- 2) Aggregate data for treemap ----
  treemap_data <- df |>
    dplyr::group_by(unhcr_region, activity_name) |>
    dplyr::summarise(
      total_funding = sum(transaction_value_USD, na.rm = TRUE),
      ## total funded by the donor - ,   transaction_provider_org == donor_name
      
      .groups = "drop"
    ) |>
    dplyr::ungroup() |> 
    dplyr::left_join(
      df |>
        dplyr::filter( transaction_provider_org == donor_name) |>
        dplyr::group_by(activity_name) |>
        dplyr::summarise(
            total_funding_donor = sum(transaction_value_USD, na.rm = TRUE),
      .groups = "drop")|>    dplyr::ungroup(),
    by= c("activity_name")) |>
    dplyr::mutate( 
      share = total_funding_donor/ total_funding  ,
      label_text =  paste0(activity_name, " - ", 
                           scales::label_number(accuracy = 0.1, scale_cut = scales::cut_short_scale())(total_funding_donor), 
                           "$ (",
                           scales::label_percent(accuracy = 0.1)(share), 
                           ")"))|>
    dplyr::filter( !(is.na(total_funding_donor))  )
  
  # Calculate overall donor total for 'share' measure type
  donor_total_overall <- sum(treemap_data$total_funding_donor, na.rm = TRUE)



  if (nrow(treemap_data) == 0) {
    stop("No valid funding data to plot after aggregation and filtering for value_to_map.")
  }
  
  # Define colors for regions (first level of treemap)
  region_colors <- unhcrthemes::unhcr_pal(n = length(unique(treemap_data$unhcr_region)), name = "pal_unhcr")
  
  # ---- 3) Plotting ----
  p <- ggplot2::ggplot(treemap_data,
                        ggplot2::aes(area = total_funding_donor,
                                     fill = unhcr_region,
                                     subgroup = unhcr_region,
                                     label = label_text)) +
    treemapify::geom_treemap() +
    treemapify::geom_treemap_subgroup_border(colour = "white", size = 3) +
      # Use multiple text layers with different placements
      treemapify::geom_treemap_subgroup_text(place = "centre",
                                             grow = T, 
                                             alpha = 0.5, 
                                             colour ="black", 
                                             fontface = "italic", 
                                             min.size = 0) +
    
      treemapify::geom_treemap_text(colour = "white", 
                                    place = "topleft", 
                                    reflow = T) + 
     # treemapify::geom_treemap_subgroup_text(
     #    place = "centre", 
     #    grow = TRUE,
     #    alpha = 0.5, 
     #    colour = "black",
     #    fontface = "bold", 
     #    min.size = 0
     #  ) +
  
      # treemapify::geom_treemap_text(
      #   colour = "white",
      #   place = "topleft",      # Different placement for first label
      #   size = label_font_size * 0.9,  # Slightly smaller for corner placement
      #   family = "Lato",
      #   grow = FALSE,           # Don't let it grow
      #   padding.x = grid::unit(2, "mm"),  # Add padding
      #   padding.y = grid::unit(2, "mm"),
      #   reflow = TRUE,          # Reflow text if too long
      #   min.size = 4            # Minimum font size
      # ) +
      # # Optional: Add secondary text with smaller size for additional info
      # treemapify::geom_treemap_text(
      #   ggplot2::aes(label = secondary_label),  # Create a secondary label column
      #   colour = "white",
      #   place = "bottomright",
      #   size = label_font_size * 0.7,
      #   family = "Lato",
      #   alpha = 0.8,
      #   grow = FALSE,
      #   min.size = 2
      # ) +
    ggplot2::scale_fill_manual(values = region_colors) +
    unhcrthemes::theme_unhcr(void = TRUE,
                             legend = FALSE, 
                             font_size = 20) +
    ggplot2::labs(
      title = paste("Portfolio of ", donor_name, " |", paste(year), ""),

      caption = "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI) - Includes Total Funding (Share of Donor's Funding within this activity)"
    )

  return(p)
}
