# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot donor earmarking
#'
#' @description This function plots the earmarking of funding from a specific donor.
#'
#' @param donor_name The name of the donor to plot.
#' @param year A numeric value or a vector of numeric values to filter on year.
#' @param by The category to group by. One of "date", "global", "region", "country", "sector".
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param ctr_name A character vector corresponding to the name of the country.
#'
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#'
#' @export
plot_donor_earmarking <- function(donor_name,
                                  year = NULL,
                                  by = "global",
                                  programme_lab = NULL,
                                  iati_identifier_ops = NULL,
                                  ctr_name = NULL) {

  # Basic data preparation
  df <- iati::dataTransaction |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier") |>
    dplyr::filter(transaction_provider_org == donor_name,
                  transaction_type_name == "Incoming Commitment")

  # Filtering
  if (!is.null(year)) {
    df <- df |> dplyr::filter(year %in% {{year}})
  }
  if (!is.null(programme_lab)) {
    df <- df |> dplyr::filter(programmme_lab == {{programme_lab}})
  } else if (!is.null(iati_identifier_ops)) {
    df <- df |> dplyr::filter(iati_identifier_ops == {{iati_identifier_ops}})
  } else if (!is.null(ctr_name)) {
    df <- df |> dplyr::filter(ctr_name == {{ctr_name}})
  }

  # Grouping and summarization logic based on 'by'
  plot_data <- switch(
    by,
    "date" = {
      df |>
        dplyr::group_by(year, earmarking_name) |>
        dplyr::summarise(total_funding = sum(transaction_value_USD, na.rm = TRUE)) |>
        dplyr::filter(!is.na(earmarking_name))
    },
    "global" = {
      df |>
        dplyr::group_by(earmarking_name) |>
        dplyr::summarise(total_funding = sum(transaction_value_USD, na.rm = TRUE)) |>
        dplyr::filter(!is.na(earmarking_name))
    },
    "region" = {
      df |>
        dplyr::group_by(unhcr_region, earmarking_name) |>
        dplyr::summarise(total_funding = sum(transaction_value_USD, na.rm = TRUE)) |>
        dplyr::filter(!is.na(unhcr_region), !is.na(earmarking_name))
    },
    "country" = {
      df |>
        dplyr::group_by(ctr_name, earmarking_name) |>
        dplyr::summarise(total_funding = sum(transaction_value_USD, na.rm = TRUE)) |>
        dplyr::filter(!is.na(ctr_name), !is.na(earmarking_name))
    },
    "sector" = {
       df |>
        dplyr::left_join(iati::dataSector, by = "iati_identifier") |>
        dplyr::filter(!is.na(sector_desc), !is.na(earmarking_name)) |>
        dplyr::group_by(sector_desc, earmarking_name) |>
        dplyr::summarise(total_funding = sum(transaction_value_USD, na.rm = TRUE))
    },
    stop("Invalid 'by' argument. Choose from 'date', 'global', 'region', 'country', 'sector'.")
  )

  p <- ggplot2::ggplot(plot_data, ggplot2::aes(y = total_funding, fill = earmarking_name)) +
    ggplot2::geom_bar(stat = "identity", position = "stack") +
    unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = "X") +
    ggplot2::scale_y_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
    ggplot2::labs(
      title = paste("Earmarking for", donor_name),
      subtitle = paste("Grouped by", by),
      x = "",
      y = "Total Funding (USD)",
      caption = "Source: IATI Data"
    )

  if (by == "global") {
      p <- p + ggplot2::aes(x = "Global")
  } else if (by == "date") {
      p <- p + ggplot2::aes(x = year)
  } else {
      p <- p + ggplot2::aes(x = .data[[by]]) + ggplot2::coord_flip()
  }

  p
}
