# WARNING - Generated by {fusen} from dev/dev_donor_focus.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot donor funding on a world map with proportional symbols
#'
#' @description
#' This function generates a world map showing funding locations for a given donor
#' and year(s). It uses proportional symbols where a white outer circle represents
#' the total funding from all donors at a location, and an inner UNHCR blue circle
#' represents the specific donor's funding at that location. The visual difference
#' between the two circles provides insight into the donor's contribution share.
#' Top locations by donor funding are highlighted with ggrepel labels.
#' The map uses a Bertin 1951-like projection (Equal Earth) for good world generalization.
#'
#' @param donor_name Character. The name of the donor to filter by.
#' @param year Numeric or integer vector. Year(s) to filter the transaction data.
#' @param top_n_locations Integer. Number of top locations (by donor funding)
#'   to label using `ggrepel`. Defaults to 5.
#' @param max_symbol_size Numeric. Maximum size for the proportional symbols.
#'   Adjust based on data range and desired visual effect. Defaults to 15.
#'
#' @return A ggplot object representing the world map.
#' @import ggplot2
#' @import dplyr
#' @import sf
#' @import rnaturalearth
#' @import rnaturalearthdata
#' @import ggrepel
#' @import scales
#' @import unhcrthemes
#'
#' @export
#' @examples
#' # Example usage:
#' plot_donor_location_map(
#'   donor_name = "Private donors",
#'   year = 2025,
#'   top_n_locations = 5,
#'   max_symbol_size = 20
#' )
plot_donor_location_map <- function(donor_name,
                                    year = NULL,
                                    top_n_locations = 5,
                                    max_symbol_size = 15) {

  # ---- 0) Basic checks ----
  if (!is.numeric(top_n_locations) || length(top_n_locations) != 1 || top_n_locations < 0) {
    stop("`top_n_locations` must be a single non-negative integer.")
  }
  if (!is.numeric(max_symbol_size) || length(max_symbol_size) != 1 || max_symbol_size <= 0) {
    stop("`max_symbol_size` must be a single positive numeric value.")
  }

  # ---- 1) Load map data ----
  # Using Bertin
  target_crs <- "+proj=bertin1953" 
  
  world_sf <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf") |>
    dplyr::filter( !(admin == "Antarctica")) |>
    sf::st_transform(crs = target_crs)

  # ---- 2) Prepare IATI data ----
  # Filter transactions for the specified donor and year(s)
  filtered_transactions <- iati::dataTransaction |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier") |>
    dplyr::filter(
      transaction_type_name == "Incoming Commitment",
      transaction_provider_org == donor_name
    ) 

  if (!is.null(year)) {
    filtered_transactions <- filtered_transactions |> dplyr::filter(year %in% .env$year)
  }

  if (nrow(filtered_transactions) == 0) {
    stop("No transaction data found for the specified donor and year(s).")
  }
  
  # Get all transactions for total funding calculation at locations
  all_transactions <- iati::dataTransaction |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier") |>
    dplyr::filter(
      transaction_type_name == "Incoming Commitment",
      transaction_provider_org == donor_name
    ) 
  
  if (!is.null(year)) {
    all_transactions <- all_transactions |> dplyr::filter(year %in% .env$year)
  }

  # Join with location data and aggregate funding using iati_identifier
  # location_type = c("UNHCR Headquarters", "UNHCR Regional Bureau", 
  # "UNHCR Country Office", "UNHCR Chargé de Mission", "UNHCR Multi-country Office", 
  # "UNHCR National Office", "UNHCR Field Office", "UNHCR Field Unit", 
  # "UNHCR Sub-Office", "UNHCR Regional Office", "UNHCR Liaison Office", 
  # "UNHCR Deputy Director Office", "UNHCR Branch Office", "UNHCR Multi-Country Office", 
  # "Global Hub / Service Center", "UNHCR Office of Special Coordinator", 
  # "UNHCR Planned Office")

  mainLocation <- iati::dataLocation |> 
    # Group and collapse multiple values
    dplyr::group_by(iati_identifier, location_type) |> 
    dplyr::summarize(
      location_ref = paste(unique(location_ref), collapse = "; "),
      .groups = "drop"
    ) |> 
    
    # Then pivot
    tidyr::pivot_wider(
      id_cols = iati_identifier,
      names_from = location_type,
      values_from = location_ref
    ) |> 
    janitor::clean_names() |>
    
    # Apply business logic - extract first value if there are multiple
    dplyr::mutate(
      across(where(is.character), 
             ~ifelse(is.na(.) | . == "", NA_character_, .)) ) |>
    
    dplyr::mutate(
      main_location_ref = dplyr::case_when(
        # Extract first HQ if exists
        !is.na(unhcr_headquarters)  ~ "CHEP000332",
        
        # Extract first bureau if exists
        !is.na(unhcr_regional_bureau)  ~ unhcr_regional_bureau,
        
        ## Regional bureau
        is.na(unhcr_headquarters) & 
          is.na(unhcr_regional_bureau) &
          is.na(unhcr_country_office) &
          is.na(unhcr_regional_bureau)  &
        !is.na(unhcr_regional_office)  ~ unhcr_regional_office,
        
        # Extract first MCO if exists
        !is.na(unhcr_multi_country_office)  ~ unhcr_multi_country_office,
        
        ## Branch office
        is.na(unhcr_headquarters) & 
          is.na(unhcr_regional_bureau) &
          is.na(unhcr_country_office) &
          is.na(unhcr_national_office) &
          !is.na(unhcr_branch_office)  ~ unhcr_branch_office,
        
        ## National office
        is.na(unhcr_headquarters) & 
          is.na(unhcr_regional_bureau) &
          is.na(unhcr_country_office) &
          is.na(unhcr_branch_office) &
          !is.na(unhcr_national_office)  ~ unhcr_national_office,
        
        ## Liaison office
        is.na(unhcr_headquarters) & 
          is.na(unhcr_regional_bureau) &
          is.na(unhcr_country_office) &
          is.na(unhcr_branch_office) &
          is.na(unhcr_national_office)&
          !is.na(unhcr_liaison_office)   ~ unhcr_liaison_office,
        
        ## Charge mission
        is.na(unhcr_headquarters) & 
          is.na(unhcr_regional_bureau) &
          is.na(unhcr_country_office) &
          is.na(unhcr_branch_office) &
          is.na(unhcr_national_office) &
          is.na(unhcr_liaison_office)  &
          !is.na(unhcr_charge_de_mission)   ~ unhcr_charge_de_mission,
        
        # Default to first country office
        .default = unhcr_country_office
      )
    ) |>
    ## Manual clean
    dplyr::mutate(
      main_location_ref = dplyr::case_when(
        main_location_ref == "AGOp000019; MOZp000256"  ~ "MOZp000256",
        main_location_ref == "MWIp000238; ZMBp000385" ~ "ZMBp000385", 
        main_location_ref == "ZWEp000389; MWIp000238; ZMBp000385" ~ "ZMBp000385", 
        main_location_ref == "CZEP000102; POLP000277" ~ "POLP000277",
        main_location_ref == "BLRP000035; RUSp000290" ~ "RUSp000290",
        main_location_ref == "MDAP000254; BLRP000035" ~ "HUNP000749",
        # Default  
        .default = main_location_ref
      )
    ) |> 
    select(main_location_ref, iati_identifier) |>
      dplyr::left_join(iati::dataLocation |>  
                         dplyr::select( location_ref, 
                                        location_lat, location_long ) |> 
                         distinct() ,
                    ## retain a single location per activity_name aka the office the most important   
                    by = c( "main_location_ref" = "location_ref") ) |>
    dplyr::rename("lat"="location_lat", "lon"="location_long")
  
  # Aggregate all donor funding per location
  all_donor_locations_funding <- all_transactions |>
    dplyr::left_join(mainLocation |> 
                       dplyr::select(main_location_ref, iati_identifier), by = "iati_identifier") |>
    dplyr::filter( !is.na(transaction_value_USD)) |>
    dplyr::filter(! is.na(main_location_ref)) |>
    dplyr::group_by(main_location_ref) |>
    dplyr::summarise(
      total_funding_all_donors = sum(transaction_value_USD, na.rm = TRUE),
      .groups = "drop"
    )  
   # sf::st_as_sf(coords = c("lon", "lat"), crs = 4326) # WGS 84
  
  # Aggregate specific donor funding per location
  donor_locations_funding <- filtered_transactions |>
    dplyr::left_join(mainLocation |>
                       dplyr::select(main_location_ref, iati_identifier), by = "iati_identifier") |>
    dplyr::filter( !is.na(transaction_value_USD)) |>
    dplyr::group_by(main_location_ref) |>
    dplyr::summarise(
      total_funding_donor = sum(transaction_value_USD, na.rm = TRUE),
      .groups = "drop"
    )  

  if (nrow(donor_locations_funding) == 0) {
    stop("No valid location data with coordinates and funding found for the specified donor.")
  }

  # Join aggregated data
  map_data <- all_donor_locations_funding |>
    dplyr::full_join(
      donor_locations_funding, #|> sf::st_drop_geometry(), # drop geometry to avoid join issues, re-add later
      by = c( "main_location_ref")
    ) |>
    dplyr::left_join(mainLocation |>
                       dplyr::select(main_location_ref, lat, lon) |>
                       unique(), by = "main_location_ref") |>
    dplyr::filter(! (is.na(main_location_ref))) |>
     sf::st_as_sf(coords = c("lon", "lat"), crs = 4326) |> # WGS 84
    dplyr::mutate(
      total_funding_donor = tidyr::replace_na(total_funding_donor, 0),
      # Add geometry back from all_donor_locations_funding
      geometry = geometry # This ensures sf object maintains its geometry
    ) |>
    # Transform to target CRS after full_join
    sf::st_transform(crs = target_crs)

  # Filter out locations with no funding from either (after joins and NA replacements)
  map_data <- map_data |>
    dplyr::filter(total_funding_all_donors > 0 | total_funding_donor > 0)
  
  if (nrow(map_data) == 0) {
    stop("No locations with funding data after joining and filtering.")
  }

  # Identify top locations for labeling
  top_locations_labels <- map_data |>
    dplyr::arrange(dplyr::desc(total_funding_donor)) |>
    dplyr::slice_head(n = top_n_locations) |>
    dplyr::mutate(
      label = paste0( "", scales::label_number(
    scale_cut = scales::cut_short_scale(), accuracy = 0.1)(total_funding_donor) , "")
    )

  # ---- 3) Define colors and sizes ----
  ocean_color <- "#E0F2F7" # Light blue
  country_fill_color <- "#D3D3D3" # Elegant gray
  country_border_color <- "#F0F0F0" # Very light white
  
  donor_color <- "#0072BC"
  all_donors_color <- "white"

  # ---- 4) Plotting ----
  p <- ggplot2::ggplot() +
    # Ocean background
    ggplot2::geom_sf(data = world_sf, fill = ocean_color, color = NA) + # Draw entire world as ocean
    
    # Countries
    ggplot2::geom_sf(data = world_sf, fill = country_fill_color, color = country_border_color, linewidth = 0.1) +
    
    # Proportional symbols for ALL donor funding (background circles)
    ggplot2::geom_sf(
      data = map_data |> dplyr::filter(total_funding_all_donors > 0),
      ggplot2::aes(size = total_funding_all_donors),
      shape = 21, fill = all_donors_color, color = "black", stroke = 0.5,
      alpha = 0.7,
      show.legend = "point"
    ) +
    
    # Proportional symbols for specific donor funding (foreground circles)
    ggplot2::geom_sf(
      data = map_data |> dplyr::filter(total_funding_donor > 0),
      ggplot2::aes(size = total_funding_donor),
      shape = 21, fill = donor_color, color = donor_color, stroke = 0.5,
      alpha = 0.8,
      show.legend = "point"
    ) +
    
    # Scale for proportional symbol sizes
    ggplot2::scale_size_continuous(
      name = "Funding (USD)",
      range = c(1, max_symbol_size) 
    ) +
    
    # Labels for top locations
    ggrepel::geom_label_repel(
      data = top_locations_labels,
      ggplot2::aes(label = label, geometry = geometry),
      stat = "sf_coordinates",
      min.segment.length = 0,
      box.padding = 0.5,
      point.padding = 0.5,
      force = 1,
      size = 7,
      direction = "both",
      color = "black"
    ) +
    
    unhcrthemes::theme_unhcr(void = TRUE, 
                             legend = FALSE,
                             font_size = 20) +
    ggplot2::theme(
      panel.background = ggplot2::element_rect(fill = ocean_color, color = NA),
      plot.background = ggplot2::element_rect(fill = ocean_color, color = NA)
    ) +
    ggplot2::labs(
      title = paste("Geographic Focus for ", donor_name, "|", year),
      caption = paste0(
        # "White circle: Total funding from all donors. UNHCR blue circle: Funding from ", donor_name, ".\n",
        # "Size indicates amount. Difference in circle size shows donor's share.\n",
        "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI)"
      )
    )

  return(p)
}
