# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot donor interest profile
#'
#' @description This function creates a bar chart showing the breakdown of a
#' donor's funding by sector or region.
#'
#' @param donor_name The name of the donor to plot.
#' @param by The category to group by. One of "sector" or "region".
#' @param year A numeric value or a vector of numeric values to filter on year.
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param ctr_name A character vector corresponding to the name of the country.
#' @param top_n The number of top categories to show.
#'
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#'
#' @export
plot_donor_interest_profile <- function(donor_name,
                                        by = "sector",
                                        year = NULL,
                                        programme_lab = NULL,
                                        iati_identifier_ops = NULL,
                                        ctr_name = NULL,
                                        top_n = 10) {

  # Basic data preparation
  df <- iati::dataTransaction |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier") |>
    dplyr::filter(transaction_provider_org == donor_name,
                  transaction_type_name == "Incoming Commitment")

  # Filtering
  if (!is.null(year)) {
    df <- df |> dplyr::filter(year %in% {{year}})
  }
  if (!is.null(programme_lab)) {
    df <- df |> dplyr::filter(programmme_lab == {{programme_lab}})
  } else if (!is.null(iati_identifier_ops)) {
    df <- df |> dplyr::filter(iati_identifier_ops == {{iati_identifier_ops}})
  } else if (!is.null(ctr_name)) {
    df <- df |> dplyr::filter(ctr_name == {{ctr_name}})
  }

  # Grouping and summarization
  if (by == "sector") {
    plot_data <- df |>
      dplyr::left_join(iati::dataSector, by = "iati_identifier") |>
      dplyr::filter(!is.na(sector_desc)) |>
      dplyr::group_by(sector_desc) |>
      dplyr::summarise(total_funding = sum(transaction_value_USD, na.rm = TRUE)) |>
      dplyr::mutate(category = forcats::fct_lump_n(
        sector_desc, n = top_n, w = total_funding, other_level = "Other Sectors"
      )) |>
      dplyr::group_by(category) |>
      dplyr::summarise(total_funding = sum(total_funding, na.rm = TRUE))
  } else if (by == "region") {
    plot_data <- df |>
      dplyr::filter(!is.na(unhcr_region)) |>
      dplyr::group_by(unhcr_region) |>
      dplyr::summarise(total_funding = sum(transaction_value_USD, na.rm = TRUE)) |>
      dplyr::mutate(category = forcats::fct_lump_n(
        unhcr_region, n = top_n, w = total_funding, other_level = "Other Regions"
      )) |>
      dplyr::group_by(category) |>
      dplyr::summarise(total_funding = sum(total_funding, na.rm = TRUE))
  } else {
    stop("Invalid 'by' argument. Choose from 'sector' or 'region'.")
  }


  # Plotting
  p <- ggplot2::ggplot(plot_data, ggplot2::aes(x = reorder(category, total_funding), y = total_funding)) +
    ggplot2::geom_col(fill = "#0072BC") +
    ggplot2::coord_flip() +
    ggplot2::scale_y_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
    unhcrthemes::theme_unhcr(grid = "X", axis = "y", axis_title = "X") +
    ggplot2::labs(
      title = paste("Interest Profile for", donor_name),
      subtitle = paste("Funding breakdown by", by),
      x = by,
      y = "Total Funding (USD)",
      caption = "Source: IATI Data"
    )

  p
}
