# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot donor earmarking flexibility over time
#'
#' @description This function creates a stacked bar chart showing the proportion
#' of each earmarking category for a specific donor over several years.
#'
#' @param donor_name The name of the donor to plot.
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param ctr_name A character vector corresponding to the name of the country.
#'
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#'
#' @export
plot_donor_earmarking_flexibility_over_time <- function(donor_name,
                                                        programme_lab = NULL,
                                                        iati_identifier_ops = NULL,
                                                        ctr_name = NULL) {

  # Basic data preparation
  df <- iati::dataTransaction |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier") |>
    dplyr::filter(transaction_provider_org == donor_name,
                  transaction_type_name == "Incoming Commitment")

  # Filtering
  if (!is.null(programme_lab)) {
    df <- df |> dplyr::filter(programmme_lab == {{programme_lab}})
  } else if (!is.null(iati_identifier_ops)) {
    df <- df |> dplyr::filter(iati_identifier_ops == {{iati_identifier_ops}})
  } else if (!is.null(ctr_name)) {
    df <- df |> dplyr::filter(ctr_name == {{ctr_name}})
  }

  # Summarization
  earmarking_over_time <- df |>
    dplyr::group_by(year, earmarking_name) |>
    dplyr::summarise(total_funding = sum(transaction_value_USD, na.rm = TRUE)) |>
    dplyr::filter(!is.na(earmarking_name))

  # Plotting
  p <- ggplot2::ggplot(earmarking_over_time, ggplot2::aes(x = year, y = total_funding, fill = earmarking_name)) +
    ggplot2::geom_bar(stat = "identity", position = "fill") +
    ggplot2::scale_y_continuous(labels = scales::percent_format()) +
    unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = "X") +
    ggplot2::labs(
      title = paste("Earmarking Flexibility Over Time for", donor_name),
      subtitle = "Proportion of funding by earmarking category",
      x = "Year",
      y = "Proportion of Total Funding",
      fill = "Earmarking Type",
      caption = "Source: IATI Data"
    )

  p
}
