# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot donor funding concentration
#'
#' @description This function creates a bar chart to visualize donor funding
#' concentration by showing the percentage of total funding from the top N donors.
#'
#' @param year A numeric value or a vector of numeric values to filter on year.
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param ctr_name A character vector corresponding to the name of the country.
#' @param top_n The number of top donors to show.
#'
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#'
#' @export
plot_donor_concentration <- function(year = NULL,
                                     programme_lab = NULL,
                                     iati_identifier_ops = NULL,
                                     ctr_name = NULL,
                                     top_n = 10) {

  # Basic data preparation
  df <- iati::dataTransaction |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier") |>
    dplyr::filter(transaction_type_name == "Incoming Commitment")

  # Filtering
  if (!is.null(year)) {
    df <- df |> dplyr::filter(year %in% {{year}})
  }
  if (!is.null(programme_lab)) {
    df <- df |> dplyr::filter(programmme_lab == {{programme_lab}})
  } else if (!is.null(iati_identifier_ops)) {
    df <- df |> dplyr::filter(iati_identifier_ops == {{iati_identifier_ops}})
  } else if (!is.null(ctr_name)) {
    df <- df |> dplyr::filter(ctr_name == {{ctr_name}})
  }

  # Summarization
  donor_summary <- df |>
    dplyr::group_by(transaction_provider_org) |>
    dplyr::summarise(total_funding = sum(transaction_value_USD, na.rm = TRUE)) |>
    dplyr::mutate(transaction_provider_org = forcats::fct_lump_n(
      transaction_provider_org,
      n = top_n,
      w = total_funding,
      other_level = "Other Donors"
    )) |>
    dplyr::group_by(transaction_provider_org) |>
    dplyr::summarise(total_funding = sum(total_funding, na.rm = TRUE)) |>
    dplyr::mutate(percentage = total_funding / sum(total_funding))

  # Plotting
  p <- ggplot2::ggplot(donor_summary, ggplot2::aes(x = reorder(transaction_provider_org, percentage), y = percentage)) +
    ggplot2::geom_col(fill = "#0072BC") +
    ggplot2::coord_flip() +
    ggplot2::scale_y_continuous(labels = scales::percent_format()) +
    unhcrthemes::theme_unhcr(grid = "X", axis = "y", axis_title = "X") +
    ggplot2::labs(
      title = "Donor Funding Concentration",
      subtitle = paste("Top", top_n, "donors and their contribution to total funding"),
      x = "Donor",
      y = "Percentage of Total Funding",
      caption = "Source: IATI Data"
    )

  p
}
