# WARNING - Generated by {fusen} from dev/dev_donor_focus.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot donor regional and programme focus as a treemap
#'
#' @description
#' This function generates a treemap visualization showing a donor's funding
#' allocation across UNHCR regions and within those regions, by programme.
#' The size of each treemap tile can represent either the absolute funding
#' amount or the share of the donor's total funding for that programme within a region.
#'
#' @param donor_name Character. The name of the donor to analyze.
#' @param year Numeric or integer vector. Year(s) to filter the data.
#' @param measure_type Character. One of "total_amount_usd" (default) or "share".
#'   - "total_amount_usd": Tile size represents the absolute USD amount.
#'   - "share": Tile size represents the share of the donor's total funding
#'     that goes to a specific programme within a specific UNHCR region.
#' @param label_font_size Numeric. Base font size for treemap labels.
#'
#' @return A ggplot object representing the treemap.
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import treemapify
#' @import unhcrthemes
#'
#' @export
#' @examples
#' # Example usage:
#' plot_donor_regional_focus_treemap(
#'   donor_name = "Private donors",
#'   year = c(2023, 2024, 2025),
#'   label_font_size = 3
#' )
#'
#' plot_donor_regional_focus_treemap(
#'   donor_name = "Private donors",
#'   year = 2025,
#'   label_font_size = 5
#' )
plot_donor_regional_focus_treemap <- function(donor_name,
                                              year = NULL,
                                              label_font_size = 4) {

  # ---- 0) Basic checks ----
  if (!is.numeric(label_font_size) || length(label_font_size) != 1 || label_font_size < 1) {
    stop("`label_font_size` must be a single numeric value >= 1.")
  }

  # ---- 1) Get IATI data ----
  df <- iati::dataTransaction |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier") |>
    dplyr::filter(
      .data$transaction_type_name == "Incoming Commitment"
    )

  # Filtering by year
  if (!is.null(year)) {
    df <- df |> dplyr::filter(.data$year %in% .env$year)
  }

  if (nrow(df) == 0) {
    stop("No data found for the selected donor and year(s).")
  }
  
  # Ensure necessary columns are not NA
  df <- df |>
    dplyr::filter(!is.na(.data$unhcr_region2), !is.na(.data$activity_name), !is.na(.data$transaction_value_USD))

  if (nrow(df) == 0) {
    stop("No data remaining after filtering out NA values for region, programme, or funding.")
  }

  # ---- 2) Aggregate data for treemap ----
  treemap_data <- df |>
    dplyr::group_by(.data$unhcr_region2, .data$activity_name) |>
    dplyr::summarise(
      total_funding = sum(.data$transaction_value_USD, na.rm = TRUE),
      ## total funded by the donor - ,   .data$transaction_provider_org == donor_name
      
      .groups = "drop"
    ) |>
    dplyr::ungroup() |> 
    dplyr::left_join(
      df |>
        dplyr::filter( transaction_provider_org == donor_name) |>
        dplyr::group_by(activity_name) |>
        dplyr::summarise(
            total_funding_donor = sum(.data$transaction_value_USD, na.rm = TRUE),
      .groups = "drop")|>    dplyr::ungroup(),
    by= c("activity_name")) |>
    dplyr::mutate( 
      share = total_funding_donor/ total_funding  ,
      label_text =  paste0(.data$activity_name, " - ", 
                           scales::label_number(accuracy = 0.1, scale_cut = scales::cut_short_scale())(.data$total_funding_donor), 
                           "$ (",
                           scales::label_percent(accuracy = 0.1)(.data$share), 
                           ")"))|>
    dplyr::filter( !(is.na(total_funding_donor))  )
  
  # Calculate overall donor total for 'share' measure type
  donor_total_overall <- sum(treemap_data$total_funding_donor, na.rm = TRUE)



  if (nrow(treemap_data) == 0) {
    stop("No valid funding data to plot after aggregation and filtering for value_to_map.")
  }
  
  # Define colors for regions (first level of treemap)
  region_colors <- unhcrthemes::unhcr_pal(n = length(unique(treemap_data$unhcr_region2)), name = "pal_unhcr")
  
  # ---- 3) Plotting ----
  p <- ggplot2::ggplot(treemap_data,
                        ggplot2::aes(area = .data$total_funding_donor,
                                     fill = .data$unhcr_region2,
                                     subgroup = .data$unhcr_region2,
                                     label = .data$label_text)) +
    treemapify::geom_treemap() +
    treemapify::geom_treemap_subgroup_border(colour = "white", size = 3) +
    treemapify::geom_treemap_subgroup_text(place = "centre", grow = TRUE,
                                           alpha = 0.5, colour = "black",
                                           fontface = "bold", min.size = 0) +
    treemapify::geom_treemap_text(
      colour = "white",
      place = "centre",
      size = label_font_size,
      family = "Lato",
      grow = TRUE
    ) +
    ggplot2::scale_fill_manual(values = region_colors) +
    unhcrthemes::theme_unhcr(font_size = 14) +
    ggplot2::theme(legend.position = "none") +
    ggplot2::labs(
      title = paste("Donor Portfolio : ", donor_name, " (", paste(range(year), collapse = "-"), ")"),
      subtitle = paste("Includes Total Funding (Share of Donor's Funding within this activity) "),
      caption = "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI)"
    )

  return(p)
}
