# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot implementing partner funding over time
#'
#' @description This function plots the funding for a specific implementing partner over time,
#' with options to group the data by different categories.
#'
#' @param partner_name The name of the implementing partner to plot.
#' @param year A numeric value or a vector of numeric values to filter on year.
#' @param by The category to group by. One of "global", "region", "country", "sector".
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param ctr_name A character vector corresponding to the name of the country.
#' @param top_n_countries The number of top countries to show when `by = "country"`.
#'
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#'
#' @export
plot_implementing_partner_funding_over_time <- function(partner_name,
                                         year = NULL,
                                         by = "global",
                                         programme_lab = NULL,
                                         iati_identifier_ops = NULL,
                                         ctr_name = NULL,
                                         top_n_countries = 10) {

  # Basic data preparation
  df <- iati::dataTransaction |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier") |>
    dplyr::left_join(iati::dataParticipating_org, by = "iati_identifier") |>
    dplyr::filter(participating_org_eng == partner_name,
                  participating_org_role_name == "Implementing",
                  transaction_type_name == "Expenditure")

  # Filtering
  if (!is.null(year)) {
    df <- df |> dplyr::filter(year.x %in% {{year}})
  }
  if (!is.null(programme_lab)) {
    df <- df |> dplyr::filter(programmme_lab == {{programme_lab}})
  } else if (!is.null(iati_identifier_ops)) {
    df <- df |> dplyr::filter(iati_identifier_ops == {{iati_identifier_ops}})
  } else if (!is.null(ctr_name)) {
    df <- df |> dplyr::filter(ctr_name.x == {{ctr_name}})
  }

  # Grouping and summarization logic based on 'by'
  plot_data <- switch(
    by,
    "global" = {
      df |>
        dplyr::group_by(year.x) |>
        dplyr::summarise(total_funding = sum(transaction_value_USD, na.rm = TRUE))
    },
    "region" = {
      df |>
        dplyr::group_by(year.x, unhcr_region) |>
        dplyr::summarise(total_funding = sum(transaction_value_USD, na.rm = TRUE)) |>
        dplyr::filter(!is.na(unhcr_region))
    },
    "country" = {
      top_countries <- df |>
        dplyr::group_by(ctr_name.x) |>
        dplyr::summarise(total = sum(transaction_value_USD, na.rm = TRUE)) |>
        dplyr::slice_max(order_by = total, n = top_n_countries) |>
        dplyr::pull(ctr_name.x)

      df |>
        dplyr::filter(ctr_name.x %in% top_countries) |>
        dplyr::group_by(year.x, ctr_name.x) |>
        dplyr::summarise(total_funding = sum(transaction_value_USD, na.rm = TRUE))
    },
    "sector" = {
      df |>
        dplyr::left_join(iati::dataSector, by = "iati_identifier") |>
        dplyr::filter(!is.na(sector_desc)) |>
        dplyr::group_by(year.x, sector_desc) |>
        dplyr::summarise(total_funding = sum(transaction_value_USD, na.rm = TRUE))
    },
    stop("Invalid 'by' argument. Choose from 'global', 'region', 'country', 'sector'.")
  )

  # Plotting
  p <- ggplot2::ggplot(plot_data, ggplot2::aes(x = year.x, y = total_funding)) +
    unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = "X") +
    ggplot2::scale_y_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
    ggplot2::labs(
      title = paste("Funding Over Time for Implementing Partner:", partner_name),
      subtitle = paste("Grouped by", by),
      x = "Year",
      y = "Total Funding (USD)",
      caption = "Source: IATI Data"
    )

  if (by == "global") {
    p <- p + ggplot2::geom_line() + ggplot2::geom_point()
  } else {
    p <- p + ggplot2::geom_line(ggplot2::aes(color = .data[[by]])) +
             ggplot2::geom_point(ggplot2::aes(color = .data[[by]]))
  }

  p
}
