# WARNING - Generated by {fusen} from dev/dev_donor_focus.Rmd: do not edit by hand # nolint: line_length_linter.


#' Plot donor activity diversification over time
#' (percentage coverage vs. benchmark lines: Top 5%, Top 10%, Top 50% donors)
#' with donor points, per-year labels (number of operations), and LOESS smoothing
#'
#' @description
#' Shows the **% of UNHCR operations (countries)** covered by a selected donor each year.
#' Adds three benchmark lines: the **average** coverage (per year) for donors ranked
#' by annual funding in the **Top 5%**, **Top 10%**, and **Top 50%**.
#' The donor’s path uses **geom_smooth(method = "loess", se = FALSE)** instead of a straight line,
#' with **points** and **`ggrepel` labels** (absolute # of countries) for the donor only.
#'
#' @param donor_name Character. Donor to highlight (`transaction_provider_org`).
#' @param start_year Optional integer. Inclusive lower bound on year.
#' @param end_year Optional integer. Inclusive upper bound on year.
#' @param loess_span Numeric (0–1+). LOESS span for donor smoothing (default 0.6).
#' @param verbose Logical. Print diagnostics (default TRUE).
#'
#' @return A ggplot object.
#'
#' @import dplyr ggplot2 scales forcats unhcrthemes
#' @importFrom tidyr pivot_longer
#' @export
#' @examples
#' # Example usage:
#' show_donor_activity_diversification( 
#'   donor_name = "Private donors", 
#'    start_year = 2022, 
#'    end_year = 2025
#' )
#'
#'
#'
show_donor_activity_diversification <- function(
  donor_name,
  start_year = NULL,
  end_year   = NULL,
  loess_span = 0.6,
  verbose    = TRUE
) {
  # ---- Data ----
  data_activity    <- iati::dataActivity
  data_transaction <- iati::dataTransaction

  # ---- Prepare joined dataset ----
  df <- data_transaction |>
    dplyr::filter(.data$transaction_type_name == "Incoming Commitment") |>
    dplyr::left_join(
      data_activity |> dplyr::select(.data$iati_identifier, .data$ctr_name),
      by = "iati_identifier"
    ) |>
    dplyr::mutate(year = lubridate::year(lubridate::ymd(.data$transaction_date))) |>
    dplyr::filter(!is.na(.data$year), !is.na(.data$ctr_name))

  # ---- Year filter ----
  if (!is.null(start_year)) df <- df |> dplyr::filter(.data$year >= start_year)
  if (!is.null(end_year))   df <- df |> dplyr::filter(.data$year <= end_year)
  if (nrow(df) == 0) stop("No data after filtering (check start_year/end_year).")

  # ---- Denominator: total # countries per year ----
  total_countries_by_year <- df |>
    dplyr::group_by(.data$year) |>
    dplyr::summarise(total_countries = dplyr::n_distinct(.data$ctr_name), .groups = "drop")

  # ---- Donor-year: countries covered & coverage % ----
  donor_countries_by_year <- df |>
    dplyr::group_by(.data$transaction_provider_org, .data$year) |>
    dplyr::summarise(
      num_countries      = dplyr::n_distinct(.data$ctr_name),
      total_funding_year = sum(.data$transaction_value_USD, na.rm = TRUE),
      .groups = "drop"
    ) |>
    dplyr::left_join(total_countries_by_year, by = "year") |>
    dplyr::mutate(coverage_pct = .data$num_countries / .data$total_countries)

  # ---- Focal donor series ----
  donor_exists <- donor_name %in% donor_countries_by_year$transaction_provider_org
  donor_series <- donor_countries_by_year |>
    dplyr::filter(.data$transaction_provider_org == .env$donor_name)

  if (!donor_exists) {
    warning("Donor '", donor_name, "' not found in filtered data. Plot will show benchmarks only.")
  }

  # Labels for donor: per-year #countries (operations)
  donor_labels_df <- NULL
  if (donor_exists && nrow(donor_series) > 0) {
    donor_labels_df <- donor_series |>
      dplyr::mutate(label_txt = as.character(.data$num_countries))
  }

  # ---- Benchmarks: Top 5%, Top 10%, Top 50% (per year) ----
  ranks <- donor_countries_by_year |>
    dplyr::group_by(.data$year) |>
    dplyr::arrange(dplyr::desc(.data$total_funding_year), .by_group = TRUE) |>
    dplyr::mutate(
      n_donors = dplyr::n(),
      rank     = dplyr::row_number(),
      # ensure at least 1 donor per threshold:
      k5  = pmax(1L, ceiling(0.05 * .data$n_donors)),
      k10 = pmax(1L, ceiling(0.10 * .data$n_donors)),
      k50 = pmax(1L, ceiling(0.50 * .data$n_donors)),
      in_top5  = .data$rank <= .data$k5,
      in_top10 = .data$rank <= .data$k10,
      in_top50 = .data$rank <= .data$k50
    ) |>
    dplyr::ungroup()

  bench <- ranks |>
    dplyr::group_by(.data$year) |>
    dplyr::summarise(
      Top5  = mean(.data$coverage_pct[.data$in_top5],  na.rm = TRUE),
      Top10 = mean(.data$coverage_pct[.data$in_top10], na.rm = TRUE),
      Top50 = mean(.data$coverage_pct[.data$in_top50], na.rm = TRUE),
      .groups = "drop"
    ) |>
    tidyr::pivot_longer(cols = c("Top5", "Top10", "Top50"),
                        names_to = "benchmark", values_to = "coverage_pct") |>
    dplyr::mutate(
      benchmark = factor(.data$benchmark, levels = c("Top50", "Top10", "Top5"))
    )

  # ---- Aesthetics ----
  col_donor <- "#0072BC"   # UNHCR blue
  col_top50 <- "#9E9E9E"   # darker grey
  col_top10 <- "#BDBDBD"   # medium grey
  col_top5  <- "#D9D9D9"   # lighter grey

  lty_top50 <- "dashed"
  lty_top10 <- "dotdash"
  lty_top5  <- "twodash"

  # ---- Titles ----
  year_range <- if (!is.null(start_year) && !is.null(end_year)) {
    paste0(start_year, "–", end_year)
  } else if (!is.null(start_year)) {
    paste0("from ", start_year)
  } else if (!is.null(end_year)) {
    paste0("through ", end_year)
  } else {
    "over time"
  }

  title_txt <- paste0("Activity Diversification for ", donor_name, " | ", year_range)
  subtitle_txt <- paste(
    "Donor’s % of UNHCR operations covered / Average coverage for Top 5%, Top 10%, and Top 50% donors (ranked by annual funding)"
  )

  # ---- Plot ----
  p <- ggplot2::ggplot() +
    # Benchmarks (three straight lines, no points)
    ggplot2::geom_smooth(
      data = bench,
      ggplot2::aes(x = .data$year, y = .data$coverage_pct,
                   color = .data$benchmark, linetype = .data$benchmark),
      method = "loess", se = FALSE, span = loess_span,
      linewidth = 1.1
    ) +
    # Donor LOESS (replaces donor geom_line)
    { if (donor_exists)
        ggplot2::geom_smooth(
          data = donor_series,
          ggplot2::aes(x = .data$year, y = .data$coverage_pct),
          method = "loess", se = FALSE, span = loess_span,
          color = col_donor, linewidth = 1.8
        )
      else ggplot2::geom_blank() } +
    # Donor points
    { if (donor_exists)
        ggplot2::geom_point(
          data = donor_series,
          ggplot2::aes(x = .data$year, y = .data$coverage_pct),
          color = col_donor, size = 4.3, stroke = 0
        )
      else ggplot2::geom_blank() } +
    # Donor per-year labels: number of countries
    { if (donor_exists && !is.null(donor_labels_df) && nrow(donor_labels_df) > 0) {
        if (requireNamespace("ggrepel", quietly = TRUE)) {
          ggrepel::geom_label_repel(
            data = donor_labels_df,
            ggplot2::aes(x = .data$year, y = .data$coverage_pct, label = .data$label_txt),
            color = col_donor, size = 4.0,
            direction = "y", max.overlaps = Inf,
            box.padding = 0.15, point.padding = 0.2,
            segment.color = col_donor, segment.size = 0.1,
            nudge_x = 0.01, hjust = 0
          )
        } else {
          ggplot2::geom_text(
            data = donor_labels_df,
            ggplot2::aes(x = .data$year, y = .data$coverage_pct, label = .data$label_txt),
            color = col_donor, size = 3.8, vjust = -0.5
          )
        }
      } else ggplot2::geom_blank() } +
    ggplot2::scale_color_manual(
      values = c("Top50" = col_top50, "Top10" = col_top10, "Top5" = col_top5),
      labels = c("Top50" = "Top 50% donors (avg)",
                 "Top10" = "Top 10% donors (avg)",
                 "Top5"  = "Top 5% donors (avg)")
    ) +
    ggplot2::scale_linetype_manual(
      values = c("Top50" = lty_top50, "Top10" = lty_top10, "Top5" = lty_top5),
      labels = c("Top50" = "Top 50% donors (avg)",
                 "Top10" = "Top 10% donors (avg)",
                 "Top5"  = "Top 5% donors (avg)")
    ) +
    ggplot2::scale_y_continuous(
      labels = scales::percent,
      limits = c(0, 1),
      expand = ggplot2::expansion(mult = c(0, 0.05))
    ) +
    ggplot2::scale_x_continuous(breaks = scales::pretty_breaks()) +
    ggplot2::labs(
      title = title_txt,
      subtitle = subtitle_txt,
      x = "Year",
      y = "% of UNHCR operations (countries) covered",
      color = NULL, linetype = NULL,
      caption = "Source: UNHCR IATI — Coverage = (# countries funded by donor) / (total distinct countries funded by any donor in year)."
    ) +
    unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE, font_size = 18) +
    ggplot2::theme(
      legend.position = "bottom",
      legend.box = "horizontal",
      legend.margin = ggplot2::margin(t = -3)
    ) +
    ggplot2::coord_cartesian(clip = "off")

  # ---- Verbose diagnostics ----
  if (verbose) {
    yrs <- range(df$year, na.rm = TRUE)
    message("Years covered: ", yrs[1], "–", yrs[2])
    message("Distinct donors in period: ", dplyr::n_distinct(df$transaction_provider_org))
    message("Distinct countries per year (min–max): ",
            min(total_countries_by_year$total_countries), "–",
            max(total_countries_by_year$total_countries))
  }

  return(p)
}

