# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand # nolint: line_length_linter.

#' Show a treemap of top funding partners
#'
#' @description This function creates a treemap to visualize the top N funding partners
#' based on their total incoming commitments for a given year and location.
#'
#' @param year A numeric value for the year.
#' @param ctr_name A character vector for the country name.
#' @param programme_lab A character vector for the programme name.
#' @param iati_identifier_ops A character vector for the operation ID.
#' @param top_n The number of top donors to display. Others will be aggregated into an "Other" category.
#'
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#'
#' @export
#' @examples
#' show_funding_partners_treemap(year = 2025, ctr_name = "Brazil", top_n = 10)
show_funding_partners_treemap <- function(year,
                                          ctr_name = NULL,
                                          programme_lab = NULL,
                                          iati_identifier_ops = NULL,
                                          top_n = 10) {

  if (!requireNamespace("treemapify", quietly = TRUE)) {
    message("Package `treemapify` is not installed. Please run `install.packages('treemapify')` to use this function.")
    return(invisible(NULL))
  }

  df <- iati::dataTransaction |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier")|> 
    dplyr::mutate(year = as.numeric(year))

  # Filtering
  if (!is.null(programme_lab)) {
    df <- df |> dplyr::filter(programmme_lab == {{programme_lab}} & year == {{year}} & transaction_type_name == "Incoming Commitment")
  } else if (!is.null(iati_identifier_ops)) {
    df <- df |> dplyr::filter(iati_identifier_ops == {{iati_identifier_ops}} & year == {{year}} & transaction_type_name == "Incoming Commitment")
  } else if (!is.null(ctr_name)) {
    df <- df  |>
      dplyr::filter(ctr_name == {{ctr_name}} & 
                              year == {{year}} & 
                              transaction_type_name == "Incoming Commitment")
  }

  df_summary <- df |>
    dplyr::group_by(provider_org_type_name, transaction_provider_org) |>
    dplyr::summarise(total_commitment = sum(transaction_value_USD, na.rm = TRUE)) |>
    dplyr::ungroup() |>
    dplyr::mutate(transaction_provider_org = forcats::fct_lump_n(
      transaction_provider_org,
      n = top_n,
      w = total_commitment,
      other_level = "Other Donors"
    )) |>
    dplyr::group_by(provider_org_type_name, transaction_provider_org) |>
    dplyr::summarise(total_commitment = sum(total_commitment, na.rm = TRUE)) |>
    dplyr::filter(total_commitment > 0)


  p <- ggplot2::ggplot(df_summary, ggplot2::aes(area = total_commitment, fill = provider_org_type_name,
                                     label = paste(transaction_provider_org,
                                                   scales::label_number(scale_cut = scales::cut_short_scale())(total_commitment),
                                                   sep = "\n"))) +
    treemapify::geom_treemap() +
    treemapify::geom_treemap_text(fontface = "italic", colour = "white", place = "centre",
                      grow = TRUE) +
    ggplot2::labs(
      title = "Top Funding Partners by Commitment",
      subtitle = paste0("For ", ctr_name %||% programme_lab %||% iati_identifier_ops, " in ", year),
      caption = "Source: IATI Data"
    ) +
    unhcrthemes::theme_unhcr(grid = FALSE, axis = FALSE, axis_text = FALSE) +
    ggplot2::scale_fill_viridis_d(option = "magma", name = "Donor Type")

  return(p)
}

`%||%` <- function(a, b) {
  if (!is.null(a)) a else b
}
