# WARNING - Generated by {fusen} from dev/dev_donor_focus.Rmd: do not edit by hand # nolint: line_length_linter.


#' Donor ranking by funding volume (lollipop) with optional WB population/GDP weighting
#'
#' See original docs above. In single-year earmarking mode, this version computes:
#'  - Total USD, Unearmarked USD, USD/GDP
#'  - Scales each to a 0–100 score across donors (min–max)
#'  - Computes ranks (best=1) per metric
#'  - Plots x=metric type, y=score; all donors grey, highlighted donor blue with rank labels.
#'
#' @export
#' @examples
#' # Example usage:
#' show_donor_ranking(  
#'    year = 2025,
#'    top_n_display = 20 )
#'
#' show_donor_ranking(
#'   donor_name = "Private donors",
#'   year = c(2023,2024,2025),
#'   top_n_display = 10
#' )
#'
#' show_donor_ranking(   
#'   donor_name = "Private donors", 
#'    year = 2023,
#'    top_n_display = 10 )
#'
#'
show_donor_ranking <- function(donor_name = NULL,
                               top_n_display = 10,
                               year = NULL,
                               ctr_name = NULL,
                               weight_by = c("none", "population", "gdp", "population_gdp"),
                               donor_country_map = NULL,
                               wb_lang = "en",
                               top_n_earmarking = 8,
                               verbose = TRUE) {

  weight_by <- match.arg(weight_by)

  # ---- 0) Basic checks ----
  if (!is.numeric(top_n_display) || length(top_n_display) != 1 || top_n_display < 1) {
    stop("`top_n_display` must be a single integer >= 1.")
  }
  if (!is.numeric(top_n_earmarking) || length(top_n_earmarking) != 1 || top_n_earmarking < 1) {
    stop("`top_n_earmarking` must be a single integer >= 1.")
  }

  # ---- 1) Get IATI data ----
  data_transaction <- iati::dataTransaction
  data_activity    <- iati::dataActivity

  # pick value column (prefer USD)
  value_col <- dplyr::case_when(
    "transaction_value_USD" %in% names(data_transaction) ~ "transaction_value_USD",
    "transaction_value"     %in% names(data_transaction) ~ "transaction_value",
    TRUE ~ NA_character_
  )
  if (is.na(value_col)) stop("Missing transaction value column (`transaction_value_USD` or `transaction_value`).")

  # parse year(s)
  years_requested <- year
  if (!is.null(years_requested)) {
    years_requested <- as.integer(years_requested)
    years_requested <- years_requested[!is.na(years_requested)]
    if (length(years_requested) == 0) years_requested <- NULL
  }
  multi_year <- !is.null(years_requested) && length(years_requested) > 1

  # ---- 2) Filter + parse dates robustly ----
  df <- data_transaction |>
    dplyr::filter(.data$transaction_type_name == "Incoming Commitment") |>
    dplyr::mutate(
      tx_date = as.Date(
        lubridate::parse_date_time(
          .data$transaction_date,
          orders = c("ymd","Ymd","ymd HMS","Ymd HMS","ymd HM","Ymd HM","dmy","mdy"),
          quiet = TRUE, tz = "UTC"
        )
      ),
      year_tx = lubridate::year(.data$tx_date),
      tx_value = as.numeric(.data[[value_col]])
    ) |>
    dplyr::filter(!is.na(.data$year_tx), !is.na(.data$tx_value))

  # join activity for recipient country + earmarking (if present)
  act_cols <- intersect(c("iati_identifier","ctr_name","earmarking_name"), names(data_activity))
  df <- df |>
    dplyr::left_join(data_activity |> dplyr::select(dplyr::all_of(act_cols)), by = "iati_identifier")

  if (!is.null(ctr_name)) {
    if (!("ctr_name" %in% names(df))) stop("ctr_name filter requested but `ctr_name` not found after join.")
    df <- df |> dplyr::filter(.data$ctr_name %in% .env$ctr_name)
  }

  # determine years_to_plot
  available_years <- sort(unique(df$year_tx))
  if (length(available_years) == 0) stop("No usable transactions after filtering.")

  if (is.null(years_requested)) {
    years_to_plot <- max(available_years, na.rm = TRUE)
    if (verbose) message("No year provided. Using latest year: ", years_to_plot)
  } else {
    missing <- setdiff(years_requested, available_years)
    if (length(missing) > 0) stop("Year(s) not found in data: ", paste(missing, collapse = ", "))
    years_to_plot <- years_requested
  }

  ref_year <- max(years_to_plot, na.rm = TRUE)

  # ---- 3) Aggregate donor totals per year (for ranking selection, multi-year branch) ----
  donor_totals_ref <- df |>
    dplyr::filter(.data$year_tx == ref_year) |>
    dplyr::group_by(.data$transaction_provider_org) |>
    dplyr::summarise(total_ref = sum(.data$tx_value, na.rm = TRUE), .groups = "drop")

  if (nrow(donor_totals_ref) == 0) stop("No data for reference year: ", ref_year)

  top_donors <- donor_totals_ref |>
    dplyr::arrange(dplyr::desc(.data$total_ref)) |>
    dplyr::slice_head(n = top_n_display) |>
    dplyr::pull(.data$transaction_provider_org) |>
    as.character()

  if (!is.null(donor_name)) {
    donor_name <- as.character(donor_name)
    if (!donor_name %in% donor_totals_ref$transaction_provider_org) {
      stop("Donor '", donor_name, "' not found in data for year ", ref_year, ".")
    }
    if (!donor_name %in% top_donors) top_donors <- unique(c(top_donors, donor_name))
  }

  df <- df |>
    dplyr::filter(.data$year_tx %in% .env$years_to_plot)

  # ---- 4) World Bank GDP (needed for USD/GDP in earmarking scoring chart) ----
  # We'll match donors to WB countries (via donor_country_map if provided; else donor name as-is).
  wb_weights <- NULL
  {
    donors_all <- sort(unique(df$transaction_provider_org))
    donor_country <- if (!is.null(donor_country_map)) {
      mapped <- donor_country_map[names(donor_country_map) %in% donors_all]
      dplyr::tibble(
        transaction_provider_org = names(mapped),
        country_name = as.character(mapped)
      )
    } else {
      dplyr::tibble(
        transaction_provider_org = donors_all,
        country_name = donors_all
      )
    }

    # WB country master
    if (requireNamespace("worldbank", quietly = TRUE)) {
      wb_countries <- worldbank::wb_country(lang = wb_lang)
      donor_country <- donor_country |>
        dplyr::left_join(
          wb_countries |> dplyr::select(country_code, country_name),
          by = "country_name"
        ) |>
        dplyr::filter(!is.na(.data$country_code))

      if (nrow(donor_country) > 0) {
        wb_raw <- worldbank::wb_data(
          indicator  = "NY.GDP.MKTP.CD",
          country    = unique(donor_country$country_code),
          lang       = wb_lang,
          start_date = min(years_to_plot),
          end_date   = max(years_to_plot)
        )
        wb_weights <- wb_raw |>
          dplyr::mutate(date = as.integer(.data$date)) |>
          dplyr::select(.data$country_code, .data$date, gdp = .data$value) |>
          dplyr::left_join(donor_country, by = "country_code") |>
          dplyr::rename(year_wb = .data$date) |>
          dplyr::filter(.data$year_wb %in% .env$years_to_plot) |>
          dplyr::select(.data$transaction_provider_org, .data$year_wb, .data$gdp)
      }
    } else if (verbose) {
      message("Package 'worldbank' not installed/available. USD/GDP metric will be NA.")
    }
  }

  
# ---- define metric_info for subtitle/title even in single-year scoring mode ----
metric_info <- list()
metric_info$title <- "Donor scoring (0–100 scaled metrics)"
metric_info$subtitle_suffix <- "Min–max scaling across donors for three metrics: Total USD, Unearmarked USD, and USD/GDP."

  
  # ===========================
  # MULTI-YEAR BRANCH (unchanged)
  # ===========================
  multi_year <- !is.null(years_requested) && length(years_requested) > 1
  if (multi_year) {
df_year <- df |>
      dplyr::group_by(.data$transaction_provider_org, .data$year_tx) |>
      dplyr::summarise(total_funding = sum(.data$tx_value, na.rm = TRUE), .groups = "drop")

    if (weight_by != "none") {
      df_year <- df_year |>
        dplyr::left_join(
          wb_weights |> dplyr::rename(year_tx = .data$year_wb) |>
            dplyr::select(.data$transaction_provider_org, .data$year_tx, .data$population, .data$gdp),
          by = c("transaction_provider_org", "year_tx")
        ) |>
        dplyr::filter(!(is.na(.data$population) & weight_by %in% c("population", "population_gdp")),
                      !(is.na(.data$gdp) & weight_by %in% c("gdp", "population_gdp"))) |>
        dplyr::mutate(metric_value = compute_metric(.data$total_funding, .data$population, .data$gdp, weight_by))
    } else {
      df_year <- df_year |>
        dplyr::mutate(metric_value = .data$total_funding)
    }

    # order by ref year
    ref_order <- df_year |>
      dplyr::filter(.data$year_tx == ref_year) |>
      dplyr::arrange(.data$metric_value) |>
      dplyr::pull(.data$transaction_provider_org) |>
      as.character()

    df_year <- df_year |>
      dplyr::mutate(
        donor = factor(.data$transaction_provider_org, levels = ref_order),
        year_f = factor(.data$year_tx, levels = sort(unique(.data$year_tx))),
        highlight = if (is.null(donor_name)) "No" else ifelse(.data$transaction_provider_org == donor_name, "Yes", "No")
      )

    df_ranges <- df_year |>
      dplyr::group_by(.data$donor) |>
      dplyr::summarise(
        xmin = min(.data$metric_value, na.rm = TRUE),
        xmax = max(.data$metric_value, na.rm = TRUE),
        .groups = "drop"
      )

    title <- paste0(
      "Donor ranking trajectory (", min(years_to_plot), "–", max(years_to_plot), ")",
      if (!is.null(ctr_name)) paste0(" — ", paste(ctr_name, collapse = ", ")) else ""
    )

    subtitle <- paste0(
      "Top ", top_n_display, " donors (selected by ", ref_year, "). ",
      "Points are annual values; color indicates year. ",
      metric_info$subtitle_suffix
    )

    p <- ggplot2::ggplot(df_year, ggplot2::aes(y = .data$donor, x = .data$metric_value)) +
      ggplot2::geom_segment(
        data = df_ranges,
        ggplot2::aes(y = .data$donor, yend = .data$donor, x = .data$xmin, xend = .data$xmax),
        inherit.aes = FALSE,
        linewidth = 1,
        color = "#B9C2CB"
      ) +
      ggplot2::geom_point(ggplot2::aes(color = .data$year_f), size = 3.8) +
      ggplot2::geom_point(
        data = dplyr::filter(df_year, .data$highlight == "Yes"),
        ggplot2::aes(color = .data$year_f),
        size = 5.2
      ) +
      ggplot2::scale_color_brewer(palette = "Set1", name = "Year") +
      ggplot2::scale_x_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
      unhcrthemes::theme_unhcr(grid = "X", axis = "Y", axis_title = FALSE, font_size = 18) +
      ggplot2::labs(title = title, subtitle = subtitle, x = metric_info$title, y = NULL,
                    caption = "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI)")

    return(p)
  }

  # ===========================
  # 7) SINGLE YEAR — EARMARKING SCORING CHART
  # ===========================
  year_single <- years_to_plot[[1]]

  if (!("earmarking_name" %in% names(df))) {
    stop("Single-year earmarking mode requires `earmarking_name` in iati::dataActivity.")
  }

  # Use ALL donors available in the selected year (to satisfy "all donors" requirement).
  df_y <- df |> dplyr::filter(.data$year_tx == .env$year_single)

  # Identify unearmarked rows (robust case-insensitive match)
  is_unearmarked <- function(x) {
    if (is.null(x)) return(rep(FALSE, length(x)))
    grepl("un.?earmark", x, ignore.case = TRUE)
  }

  # Per-donor totals for the selected year
  donor_totals_year <- df_y |>
    dplyr::group_by(.data$transaction_provider_org) |>
    dplyr::summarise(
      total_usd       = sum(.data$tx_value, na.rm = TRUE),
      unearmarked_usd = sum(dplyr::if_else(is_unearmarked(.data$earmarking_name), .data$tx_value, 0), na.rm = TRUE),
      .groups = "drop"
    )

  # Attach GDP (if available) for USD/GDP
  if (!is.null(wb_weights)) {
    donor_totals_year <- donor_totals_year |>
      dplyr::left_join(
        wb_weights |> dplyr::filter(.data$year_wb == .env$year_single) |>
          dplyr::select(.data$transaction_provider_org, .data$gdp),
        by = "transaction_provider_org"
      )
  } else {
    donor_totals_year <- donor_totals_year |> dplyr::mutate(gdp = NA_real_)
  }

  donor_totals_year <- donor_totals_year |>
    dplyr::mutate(
      usd_per_gdp = ifelse(!is.na(.data$gdp) & .data$gdp > 0, .data$total_usd / .data$gdp, NA_real_)
    )

  # ---- Scoring helpers (min–max to 0–100) ----
  minmax_score <- function(v) {
    if (all(is.na(v))) return(rep(NA_real_, length(v)))
    vv <- v
    rng <- range(vv, na.rm = TRUE)
    if (rng[1] == rng[2]) {
      # all equal -> assign full score 100
      return(ifelse(is.na(vv), NA_real_, 100))
    }
    100 * (vv - rng[1]) / (rng[2] - rng[1])
  }

  # Compute scores & ranks per metric
  scored <- donor_totals_year |>
    dplyr::mutate(
      score_total       = minmax_score(.data$total_usd),
      score_unearmarked = minmax_score(.data$unearmarked_usd),
      score_usd_gdp     = minmax_score(.data$usd_per_gdp),
      # Ranks: best (highest value) = 1; ties get same min_rank
      rk_total          = dplyr::if_else(is.na(.data$total_usd),       NA_integer_, dplyr::min_rank(dplyr::desc(.data$total_usd))),
      rk_unearmarked    = dplyr::if_else(is.na(.data$unearmarked_usd), NA_integer_, dplyr::min_rank(dplyr::desc(.data$unearmarked_usd))),
      rk_usd_gdp        = dplyr::if_else(is.na(.data$usd_per_gdp),     NA_integer_, dplyr::min_rank(dplyr::desc(.data$usd_per_gdp)))
    )

  # Count N (non-NA) donors per metric for labeling "Rk X/N"
  N_total       <- sum(!is.na(scored$total_usd))
  N_unearmarked <- sum(!is.na(scored$unearmarked_usd))
  N_usd_gdp     <- sum(!is.na(scored$usd_per_gdp))

  # Long format for plotting
  plot_df <- scored |>
    tidyr::pivot_longer(
      cols = c(score_total, score_unearmarked, score_usd_gdp,
               rk_total, rk_unearmarked, rk_usd_gdp),
      names_to = c(".value","metric"),
      names_pattern = "(score|rk)_(total|unearmarked|usd_gdp)"
    ) |>
    dplyr::mutate(
      metric = factor(metric,
                      levels = c("total","unearmarked","usd_gdp"),
                      labels = c("Total USD","Unearmarked USD","USD/GDP")),
      # rank label with proper denominator per metric
      rk_lab = dplyr::case_when(
        metric == "Total USD"       ~ ifelse(!is.na(.data$rk), paste0("Rk ", .data$rk, "/", N_total), NA_character_),
        metric == "Unearmarked USD" ~ ifelse(!is.na(.data$rk), paste0("Rk ", .data$rk, "/", N_unearmarked), NA_character_),
        metric == "USD/GDP"         ~ ifelse(!is.na(.data$rk), paste0("Rk ", .data$rk, "/", N_usd_gdp), NA_character_)
      )
    )

  
 # Determine if we have a highlighted donor
  has_focus <- !is.null(donor_name) && donor_name %in% plot_df$transaction_provider_org

  # Split data for plotting
  if (has_focus) {
    df_focus  <- dplyr::filter(plot_df, .data$transaction_provider_org == .env$donor_name)
    df_others <- dplyr::filter(plot_df, .data$transaction_provider_org != .env$donor_name)
  } else {
    df_focus  <- NULL
    df_others <- NULL
  }
  df_all <- plot_df

  # Aesthetics
  col_all   <- scales::alpha("#8E99A4", 0.35)  # light grey, transparent
  col_focus <- "#0072BC"                       # UNHCR blue
  size_all   <- 3.0
  size_focus <- 4.6

  # Base plot
  p <- ggplot2::ggplot(mapping = ggplot2::aes(x = metric, y = score))

  if (has_focus) {
    # grey: others only
    p <- p + ggplot2::geom_point(
      data = df_others,
      color = col_all, size = size_all,
      position = ggplot2::position_jitter(width = 0.08, height = 0, seed = 42),
      na.rm = TRUE
    )
    # blue: highlighted donor
    p <- p + ggplot2::geom_point(
      data = df_focus,
      color = col_focus, size = size_focus,
      na.rm = TRUE
    )
    # labels for highlighted donor (rank per metric)
    if (requireNamespace("ggrepel", quietly = TRUE)) {
      p <- p + ggrepel::geom_text_repel(
        data = dplyr::filter(df_focus, !is.na(rk_lab)),
        ggplot2::aes(label = rk_lab),
        color = col_focus, size = 4.2,
        direction = "y", box.padding = 0.15, point.padding = 0.25,
        segment.color = "grey60", segment.size = 0.3, min.segment.length = 0,
        nudge_y = 2.5, na.rm = TRUE
      )
    } else {
      p <- p + ggplot2::geom_text(
        data = dplyr::filter(df_focus, !is.na(rk_lab)),
        ggplot2::aes(label = rk_lab),
        color = col_focus, size = 4.0, vjust = -0.7, na.rm = TRUE
      )
    }
  } else {
    # No highlighted donor: plot everyone in grey
    p <- p + ggplot2::geom_point(
      data = df_all,
      color = col_all, size = size_all,
      position = ggplot2::position_jitter(width = 0.08, height = 0, seed = 42),
      na.rm = TRUE
    )
  }

  # Scales, labels, theme
  p <- p +
    ggplot2::scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, by = 20)) +
    ggplot2::labs(
      title = paste0("Donor scoring (", year_single, ") — ",
                     ifelse(has_focus, donor_name, "All donors")),
      subtitle = "Scores: min–max across donors per metric. Blue = selected donor; label shows rank within each metric.",
      x = "Score type",
      y = "Score (0–100)",
      caption = "Metrics per donor: Total USD; Unearmarked USD (case-insensitive match on 'unearmark'); USD/GDP (WB current US$)."
    ) +
    unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE, font_size = 18) +
    ggplot2::theme(legend.position = "none")

  if (verbose) {
    message("Single-year earmarking scoring built for year: ", year_single)
    message("Donors included: ", nrow(donor_totals_year))
    message("USD/GDP available for ", N_usd_gdp, " donors (",
            sum(is.na(scored$usd_per_gdp)), " without GDP).")
    if (!has_focus) message("Tip: pass donor_name = '...' to highlight a donor in blue.")
  }

  return(p)

}

