# WARNING - Generated by {fusen} from dev/dev_donor_focus.Rmd: do not edit by hand # nolint: line_length_linter.


#' Plot donor funding over time (bar chart)
#'
#' @description
#' This function plots the funding from a specific donor over time as a bar chart.
#' If `by` is not "global", the plot is faceted by the corresponding `by` variable.
#'
#' @param donor_name The name of the donor to plot.
#' @param year A numeric value or a vector of numeric values to filter on year.
#' @param by The category to group by. One of "global", "region", "country", "earmarking_name".
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param ctr_name A character vector corresponding to the name of the country.
#' @param top_n_countries The number of top countries to show when `by = "country"`.
#'
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#'
#' @export
#' @examples
#' show_donor_funding_over_time(donor_name = "Private donors",
#'                                          year = c(2022, 2023, 20234, 2025),
#'                                          by = "global" )
#' show_donor_funding_over_time(donor_name = "Private donors",
#'                                          year = c(2022, 2023, 20234, 2025),
#'                                          by = "region" )
#' show_donor_funding_over_time(donor_name = "Private donors",
#'                                          year = c(2022, 2023, 20234, 2025),
#'                                          by = "earmarking_name" )
#' show_donor_funding_over_time(donor_name = "Private donors",
#'                                          year = c(2022, 2023, 20234, 2025),
#'                                          by = "country",
#'                                          top_n_countries = 10)
#'
show_donor_funding_over_time <- function(donor_name,
                                         year = NULL,
                                         by = "global",
                                         programme_lab = NULL,
                                         iati_identifier_ops = NULL,
                                         ctr_name = NULL,
                                         top_n_countries = 10) {

  # Basic data preparation
  df <- iati::dataTransaction |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier") |>
    dplyr::filter(
      transaction_provider_org == donor_name,
      transaction_type_name == "Incoming Commitment"
    )

  # Filtering (vector-friendly)
  if (!is.null(year)) {
    df <- df |> dplyr::filter(year %in% year)
  }
  if (!is.null(programme_lab)) {
    df <- df |> dplyr::filter(programme_lab %in% programme_lab)
  } else if (!is.null(iati_identifier_ops)) {
    df <- df |> dplyr::filter(iati_identifier_ops %in% iati_identifier_ops)
  } else if (!is.null(ctr_name)) {
    df <- df |> dplyr::filter(ctr_name %in% ctr_name)
  }

  # Ensure year is an ordered factor (nice bar ordering) - robust to char/numeric
  df <- df |>
    dplyr::mutate(
      year = suppressWarnings(as.numeric(as.character(year))),
      year = factor(year, levels = sort(unique(year), na.last = TRUE))
    )

  # Determine grouping variable (for faceting when by != global)
  facet_var <- switch(
    by,
    "global" = NULL,
    "region" = "unhcr_region",
    "country" = "ctr_name",
    "earmarking_name" = "earmarking_name",
    stop("Invalid 'by' argument. Choose from 'global', 'region', 'country', 'earmarking_name'.")
  )



  # If by == country: keep only top N countries overall (across years)
  if (identical(by, "country")) {
    top_countries <- df |>
      dplyr::group_by(ctr_name) |>
      dplyr::summarise(
        total = sum(transaction_value_USD, na.rm = TRUE),
        .groups = "drop"
      ) |>
      dplyr::slice_max(order_by = total, n = top_n_countries, with_ties = FALSE) |>
      dplyr::pull(ctr_name)

    df <- df |> dplyr::filter(ctr_name %in% top_countries)
  }

  # Drop NA levels for facet var (after any mapping above)
  if (!is.null(facet_var)) {
    df <- df |> dplyr::filter(!is.na(.data[[facet_var]]))
  }

  # Summarise
  if (is.null(facet_var)) {
    show_data <- df |>
      dplyr::group_by(year) |>
      dplyr::summarise(
        total_funding = sum(transaction_value_USD, na.rm = TRUE),
        .groups = "drop"
      )
  } else {
    show_data <- df |>
      dplyr::group_by(year, .data[[facet_var]]) |>
      dplyr::summarise(
        total_funding = sum(transaction_value_USD, na.rm = TRUE),
        .groups = "drop"
      )
  }

  # Subtitle logic (mentions top_n_countries when by == "country")
  subtitle_txt <- if (is.null(facet_var)) {
    "Overall (Global)"
  } else if (identical(by, "country")) {
    paste0("Grouped by country — top ", top_n_countries, " countries")
  } else {
    paste("Grouped by", by)
  }

  # Plot (bar chart only)
  p <- ggplot2::ggplot(show_data, ggplot2::aes(x = year, y = total_funding)) +
    ggplot2::geom_col(fill = "#0072BC") +
    unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = "X", font_size = 20, legend = FALSE) +
    ggplot2::scale_y_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
    ggplot2::labs(
      title = paste("Funding Over Time from", donor_name),
      subtitle = subtitle_txt,
      x = "Year",
      y = "Total Funding (USD)",
      caption = "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI)"
    )

  # Facet if not global
  if (!is.null(facet_var)) {
    p <- p + ggplot2::facet_wrap(stats::as.formula(paste("~", facet_var)))
  }

  p
}

