# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand # nolint: line_length_linter.

#' Show donor earmarking profiles
#'
#' @description This function creates a stacked bar chart to show the earmarking
#' profile of the top N donors.
#'
#' @param year A numeric value for the year.
#' @param ctr_name A character vector for the country name.
#' @param programme_lab A character vector for the programme name.
#' @param iati_identifier_ops A character vector for the operation ID.
#' @param top_n The number of top donors to display.
#'
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#' @import forcats
#'
#' @export
#' @examples
#' show_donor_earmarking_profile(year = 2025, ctr_name = "Brazil", top_n = 10)
show_donor_earmarking_profile <- function(year,
                                          ctr_name = NULL,
                                          programme_lab = NULL,
                                          iati_identifier_ops = NULL,
                                          top_n = 10) {

  df <- iati::dataTransaction |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier")

  # Filtering
  if (!is.null(programme_lab)) {
    df <- df |> dplyr::filter(programmme_lab == {{programme_lab}} & year == {{year}} & transaction_type_name == "Incoming Commitment")
  } else if (!is.null(iati_identifier_ops)) {
    df <- df |> dplyr::filter(iati_identifier_ops == {{iati_identifier_ops}} & year == {{year}} & transaction_type_name == "Incoming Commitment")
  } else if (!is.null(ctr_name)) {
    df <- df |> dplyr::filter(ctr_name == {{ctr_name}} & year == {{year}} & transaction_type_name == "Incoming Commitment")
  }

  # Summarize total contributions per donor
  donor_totals <- df |>
    dplyr::group_by(transaction_provider_org) |>
    dplyr::summarise(total = sum(transaction_value_USD, na.rm = TRUE)) |>
    dplyr::slice_max(order_by = total, n = top_n)

  df_summary <- df |>
    dplyr::filter(transaction_provider_org %in% donor_totals$transaction_provider_org) |>
    dplyr::group_by(transaction_provider_org, earmarking_name) |>
    dplyr::summarise(total_commitment = sum(transaction_value_USD, na.rm = TRUE)) |>
    dplyr::ungroup()

  p <- ggplot2::ggplot(df_summary,
                       ggplot2::aes(x = stats::reorder(transaction_provider_org, total_commitment, FUN = sum),
                                    y = total_commitment,
                                    fill = earmarking_name)) +
    ggplot2::geom_bar(stat = "identity", position = "stack") +
    ggplot2::coord_flip() +
    unhcrthemes::theme_unhcr(grid = "X", axis = "y", axis_title = "X") +
    ggplot2::scale_y_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
    ggplot2::scale_fill_viridis_d(option = "cividis", name = "Earmarking Type") +
    ggplot2::labs(
      title = "Donor Earmarking Profile",
      subtitle = paste0("Top ", top_n, " donors for ", ctr_name %||% programme_lab %||% iati_identifier_ops, " in ", year),
      caption = "Source: IATI Data",
      x = "Donor",
      y = "Total Commitment (USD)"
    )

  return(p)
}
