# WARNING - Generated by {fusen} from dev/dev_donor_focus.Rmd: do not edit by hand # nolint: line_length_linter.

#' Generate Donor Ranking Visualizations with Scoring Metrics
#'
#' This function creates two types of visualizations:
#' 1. **Multi-year trajectory**: Shows donor ranking changes across multiple years
#' 2. **Single-year scoring**: Creates a lollipop plot comparing donors across three
#'    scaled metrics (0-100) with optional World Bank population/GDP weighting
#'
#' In single-year mode, the function computes:
#' - **Total USD**: All incoming commitments
#' - **Unearmarked USD**: Funds marked as "unearmarked" (case-insensitive)
#' - **USD/GDP**: Total USD divided by donor country GDP (from World Bank)
#' Each metric is scaled 0-100 across donors (min-max scaling) and ranks are computed.
#'
#' @param donor_name Character. Specific donor to highlight in the visualization.
#'   If NULL, all donors are shown in equal color. For single-year scoring, the
#'   highlighted donor appears in blue with rank labels.
#' @param top_n_display Integer. Number of top donors to display in multi-year
#'   trajectory plots (ranked by reference year total).
#' @param year Integer or vector of integers. Year(s) to analyze. If NULL, uses
#'   the latest available year. If multiple years provided, creates trajectory plot.
#' @param ctr_name Character vector. Filter for specific recipient country/countries.
#'   If NULL, includes all countries.
#' @param weight_by Character. Weighting method for multi-year trajectory:
#'   - "none": Raw USD values
#'   - "population": USD per capita
#'   - "gdp": USD per GDP
#'   - "population_gdp": USD per capita per GDP
#' @param donor_country_map Named character vector. Optional mapping from donor
#'   organization names to World Bank country names for GDP/population lookups.
#'   Format: c("donor_org" = "country_name")
#' @param wb_lang Character. Language for World Bank country names ("en", "fr", etc.).
#' @param top_n_earmarking Integer. For single-year scoring, number of top
#'   earmarking categories to display (not currently used in scoring mode).
#' @param verbose Logical. If TRUE, prints progress messages and data summaries.
#'
#' @return A ggplot2 object. The plot type depends on input parameters:
#'   - Multi-year: Ranking trajectory with connected points
#'   - Single-year: Lollipop scoring plot with three metrics (0-100 scale)
#'
#' @importFrom dplyr filter mutate select group_by summarise arrange desc
#'   left_join pull slice_head case_when if_else all_of rename
#' @importFrom tidyr pivot_longer
#' @importFrom lubridate parse_date_time year
#' @importFrom ggplot2 ggplot aes geom_point geom_segment geom_text
#'   scale_color_brewer scale_x_continuous scale_y_continuous labs theme
#'   element_text
#' @importFrom scales label_number cut_short_scale alpha
#' @importFrom unhcrthemes theme_unhcr
#' @importFrom rlang .env .data
#' @importFrom stats na.omit
#'
#' @export
#'
#' @examples
#' # Single-year scoring for all donors
#' show_donor_ranking(year = 2023)
#'
#' # Highlight specific donor in single-year scoring
#' show_donor_ranking(donor_name = "USA", year = 2023)
#'
#' # Multi-year trajectory for top 15 donors
#' show_donor_ranking(year = 2020:2023, top_n_display = 15)
#'
#' # With country filtering
#' show_donor_ranking(
#'   year = 2023,
#'   ctr_name = c("Ukraine", "Syria"),
#'   donor_name = "Germany"
#' )
#'
#' # With GDP weighting in multi-year mode
#' show_donor_ranking(
#'   year = 2020:2022,
#'   weight_by = "gdp",
#'   top_n_display = 10
#' )
#' # Example usage:
#' show_donor_ranking(  
#'    year = 2025,
#'    top_n_display = 20 )
#'
#' show_donor_ranking(
#'   donor_name = "Private donors",
#'   year = c(2023,2024,2025),
#'   top_n_display = 10
#' )
#'
#' show_donor_ranking(   
#'   donor_name = "Private donors", 
#'    year = 2023,
#'    top_n_display = 10 )
#'
#'
show_donor_ranking <- function(donor_name = NULL,
                               top_n_display = 10,
                               year = NULL,
                               ctr_name = NULL,
                               weight_by = c("none", "population", "gdp", "population_gdp"),
                               donor_country_map = NULL,
                               wb_lang = "en",
                               top_n_earmarking = 8,
                               verbose = TRUE) {
  
  # ---- Argument validation ----
  weight_by <- match.arg(weight_by)
  
  if (!is.numeric(top_n_display) || length(top_n_display) != 1 || top_n_display < 1) {
    stop("`top_n_display` must be a single integer >= 1.")
  }
  if (!is.numeric(top_n_earmarking) || length(top_n_earmarking) != 1 || top_n_earmarking < 1) {
    stop("`top_n_earmarking` must be a single integer >= 1.")
  }
  
  # ---- 1. Data preparation ----
  data_transaction <- iati::dataTransaction
  data_activity <- iati::dataActivity
  
  # Determine value column
  value_col <- if ("transaction_value_USD" %in% names(data_transaction)) {
    "transaction_value_USD"
  } else if ("transaction_value" %in% names(data_transaction)) {
    "transaction_value"
  } else {
    stop("No transaction value column found. Need 'transaction_value_USD' or 'transaction_value'.")
  }
  
  # Parse year(s)
  years_requested <- if (!is.null(year)) {
    yrs <- as.integer(year)
    yrs <- yrs[!is.na(yrs)]
    if (length(yrs) == 0) NULL else yrs
  } else {
    NULL
  }
  
  multi_year_mode <- !is.null(years_requested) && length(years_requested) > 1
  
  # ---- 2. Transaction data processing ----
  df <- data_transaction |>
    dplyr::filter(.data$transaction_type_name == "Incoming Commitment") |>
    dplyr::mutate(
      tx_date = as.Date(
        lubridate::parse_date_time(
          .data$transaction_date,
          orders = c("ymd", "Ymd", "ymd HMS", "Ymd HMS", "ymd HM", "Ymd HM", "dmy", "mdy"),
          quiet = TRUE,
          tz = "UTC"
        )
      ),
      year_tx = lubridate::year(.data$tx_date),
      tx_value = as.numeric(.data[[value_col]])
    ) |>
    dplyr::filter(!is.na(.data$year_tx), !is.na(.data$tx_value))
  
  # Join activity data
  act_cols <- intersect(c("iati_identifier", "ctr_name", "earmarking_name"), names(data_activity))
  df <- df |>
    dplyr::left_join(
      data_activity |> dplyr::select(dplyr::all_of(act_cols)),
      by = "iati_identifier"
    )
  
  # Apply recipient country filter if specified
  if (!is.null(ctr_name)) {
    if (!("ctr_name" %in% names(df))) {
      stop("ctr_name filter requested but `ctr_name` column not found in data.")
    }
    df <- df |> dplyr::filter(.data$ctr_name %in% .env$ctr_name)
  }
  
  # Determine years to analyze
  available_years <- sort(unique(df$year_tx))
  if (length(available_years) == 0) stop("No usable transactions after filtering.")
  
  if (is.null(years_requested)) {
    years_to_plot <- max(available_years, na.rm = TRUE)
    if (verbose) message("No year provided. Using latest year: ", years_to_plot)
  } else {
    missing_years <- setdiff(years_requested, available_years)
    if (length(missing_years) > 0) {
      stop("Year(s) not found in data: ", paste(missing_years, collapse = ", "))
    }
    years_to_plot <- years_requested
  }
  
  ref_year <- max(years_to_plot, na.rm = TRUE)
  
  # ---- 3. Identify top donors (for multi-year trajectory) ----
  donor_totals_ref <- df |>
    dplyr::filter(.data$year_tx == .env$ref_year) |>
    dplyr::group_by(.data$transaction_provider_org) |>
    dplyr::summarise(total_ref = sum(.data$tx_value, na.rm = TRUE), .groups = "drop")
  
  if (nrow(donor_totals_ref) == 0) {
    stop("No data for reference year: ", ref_year)
  }
  
  top_donors <- donor_totals_ref |>
    dplyr::arrange(dplyr::desc(.data$total_ref)) |>
    dplyr::slice_head(n = top_n_display) |>
    dplyr::pull(.data$transaction_provider_org) |>
    as.character()
  
  # Add user-specified donor if not already in top list
  if (!is.null(donor_name)) {
    donor_name <- as.character(donor_name)
    if (!donor_name %in% donor_totals_ref$transaction_provider_org) {
      stop("Donor '", donor_name, "' not found in data for year ", ref_year, ".")
    }
    if (!donor_name %in% top_donors) {
      top_donors <- unique(c(top_donors, donor_name))
    }
  }
  
  # Filter to selected years
  df <- df |> dplyr::filter(.data$year_tx %in% .env$years_to_plot)
  
  # ---- 4. World Bank data for GDP/population weighting ----
  wb_weights <- NULL
  if (multi_year_mode && weight_by != "none") {
    donors_all <- sort(unique(df$transaction_provider_org))
    
    # Map donors to countries
    donor_country <- if (!is.null(donor_country_map)) {
      mapped <- donor_country_map[names(donor_country_map) %in% donors_all]
      dplyr::tibble(
        transaction_provider_org = names(mapped),
        country_name = as.character(mapped)
      )
    } else {
      dplyr::tibble(
        transaction_provider_org = donors_all,
        country_name = donors_all
      )
    }
    
    # Fetch World Bank data if available
    if (requireNamespace("worldbank", quietly = TRUE)) {
      wb_countries <- worldbank::wb_country(lang = wb_lang)
      
      donor_country <- donor_country |>
        dplyr::left_join(
          wb_countries |> dplyr::select(.data$country_code, .data$country_name),
          by = "country_name"
        ) |>
        dplyr::filter(!is.na(.data$country_code))
      
      if (nrow(donor_country) > 0) {
        # Determine indicators needed based on weighting method
        indicators <- switch(weight_by,
          "population" = c("SP.POP.TOTL"),
          "gdp" = c("NY.GDP.MKTP.CD"),
          "population_gdp" = c("SP.POP.TOTL", "NY.GDP.MKTP.CD"),
          "none" = NULL
        )
        
        if (!is.null(indicators)) {
          wb_raw <- worldbank::wb_data(
            indicator = indicators,
            country = unique(donor_country$country_code),
            lang = wb_lang,
            start_date = min(years_to_plot),
            end_date = max(years_to_plot)
          )
          
          wb_weights <- wb_raw |>
            dplyr::mutate(year_wb = as.integer(.data$date)) |>
            dplyr::select(.data$country_code, .data$year_wb, dplyr::any_of(c("population" = "SP.POP.TOTL", "gdp" = "NY.GDP.MKTP.CD"))) |>
            dplyr::left_join(donor_country, by = "country_code") |>
            dplyr::filter(.data$year_wb %in% .env$years_to_plot) |>
            dplyr::select(.data$transaction_provider_org, .data$year_wb, dplyr::any_of(c("population", "gdp")))
        }
      }
    } else if (verbose) {
      message("Package 'worldbank' not installed. GDP/population weighting unavailable.")
    }
  }
  
  # ---- 5. Multi-year trajectory plot ----
  if (multi_year_mode) {
    return(create_multi_year_plot(
      df = df,
      years_to_plot = years_to_plot,
      ref_year = ref_year,
      top_donors = top_donors,
      donor_name = donor_name,
      ctr_name = ctr_name,
      weight_by = weight_by,
      wb_weights = wb_weights,
      top_n_display = top_n_display
    ))
  }
  
  # ---- 6. Single-year scoring plot ----
  year_single <- years_to_plot[[1]]
  
  if (!("earmarking_name" %in% names(df))) {
    stop("Single-year scoring requires `earmarking_name` column in iati::dataActivity.")
  }
  
  # Filter to single year
  df_y <- df |> dplyr::filter(.data$year_tx == .env$year_single)
  
  # Helper function to identify unearmarked funds
  is_unearmarked <- function(x) {
    if (is.null(x)) return(rep(FALSE, length(x)))
    grepl("un.?earmark", x, ignore.case = TRUE)
  }
  
  # Calculate donor metrics
  donor_metrics <- df_y |>
    dplyr::group_by(.data$transaction_provider_org) |>
    dplyr::summarise(
      total_usd = sum(.data$tx_value, na.rm = TRUE),
      unearmarked_usd = sum(dplyr::if_else(is_unearmarked(.data$earmarking_name), .data$tx_value, 0), na.rm = TRUE),
      .groups = "drop"
    )
  
  # Add GDP data if available
  if (!is.null(wb_weights)) {
    donor_metrics <- donor_metrics |>
      dplyr::left_join(
        wb_weights |>
          dplyr::filter(.data$year_wb == .env$year_single) |>
          dplyr::select(.data$transaction_provider_org, .data$gdp),
        by = "transaction_provider_org"
      )
  } else {
    donor_metrics <- donor_metrics |> dplyr::mutate(gdp = NA_real_)
  }
  
  donor_metrics <- donor_metrics |>
    dplyr::mutate(
      usd_per_gdp = ifelse(!is.na(.data$gdp) & .data$gdp > 0, .data$total_usd / .data$gdp, NA_real_)
    )
  
    # ---- 7. Scoring and ranking ----
    # Min-max scaling helper
    minmax_score <- function(v) {
      if (all(is.na(v))) return(rep(NA_real_, length(v)))
      vv <- v
      rng <- range(vv, na.rm = TRUE)
      if (rng[1] == rng[2]) {
        return(ifelse(is.na(vv), NA_real_, 100))  # All equal -> max score
      }
      100 * (vv - rng[1]) / (rng[2] - rng[1])
    }
    
    # Determine which metrics to include
    include_gdp <- sum(!is.na(donor_metrics$usd_per_gdp)) > 1  # Need at least 2 donors with GDP data
    
    # Compute scores and ranks
    scored <- donor_metrics |>
      dplyr::mutate(
        score_total = minmax_score(.data$total_usd),
        score_unearmarked = minmax_score(.data$unearmarked_usd),
        rk_total = dplyr::if_else(
          is.na(.data$total_usd),
          NA_integer_,
          dplyr::min_rank(dplyr::desc(.data$total_usd))
        ),
        rk_unearmarked = dplyr::if_else(
          is.na(.data$unearmarked_usd),
          NA_integer_,
          dplyr::min_rank(dplyr::desc(.data$unearmarked_usd))
        )
      )
    
    # Conditionally add GDP scoring
    if (include_gdp) {
      scored <- scored |>
        dplyr::mutate(
          score_usd_gdp = minmax_score(.data$usd_per_gdp),
          rk_usd_gdp = dplyr::if_else(
            is.na(.data$usd_per_gdp),
            NA_integer_,
            dplyr::min_rank(dplyr::desc(.data$usd_per_gdp))
          )
        )
      if (verbose) {
        message("Including USD/GDP metric (", sum(!is.na(scored$usd_per_gdp)), 
                " donors have GDP data)")
      }
    } else {
      if (verbose) {
        message("Excluding USD/GDP metric - insufficient data (only ", 
                sum(!is.na(donor_metrics$usd_per_gdp)), 
                " donors have GDP data)")
      }
    }
  
  # Prepare column selection based on available metrics
  score_cols <- c("score_total", "score_unearmarked")
  rank_cols <- c("rk_total", "rk_unearmarked")
  metric_labels <- c("Total USD", "Unearmarked USD")
  metric_levels <- c("total", "unearmarked")
  
  if (include_gdp) {
    score_cols <- c(score_cols, "score_usd_gdp")
    rank_cols <- c(rank_cols, "rk_usd_gdp")
    metric_labels <- c(metric_labels, "USD/GDP")
    metric_levels <- c(metric_levels, "usd_gdp")
  }
  
  # Reshape for plotting
  plot_df <- scored |>
    tidyr::pivot_longer(
      cols = dplyr::all_of(c(score_cols, rank_cols)),
      names_to = c(".value", "metric"),
      names_pattern = "(score|rk)_(total|unearmarked|usd_gdp)"
    ) |>
    dplyr::mutate(
      metric = factor(.data$metric,
        levels = metric_levels,
        labels = metric_labels
      )
    )
  # Count donors per metric for denominator in rank labels
  N_total <- sum(!is.na(scored$total_usd))
  N_unearmarked <- sum(!is.na(scored$unearmarked_usd))
  N_usd_gdp <- if (include_gdp) sum(!is.na(scored$usd_per_gdp)) else 0
  
  # Add rank labels
  plot_df <- plot_df |>
    dplyr::mutate(
      rk_lab = dplyr::case_when(
        .data$metric == "Total USD" & !is.na(.data$rk) ~ paste0("Rk ", .data$rk, "/", N_total),
        .data$metric == "Unearmarked USD" & !is.na(.data$rk) ~ paste0("Rk ", .data$rk, "/", N_unearmarked),
        .data$metric == "USD/GDP" & !is.na(.data$rk) & include_gdp ~ paste0("Rk ", .data$rk, "/", N_usd_gdp),
        TRUE ~ NA_character_
      )
    )


  # ---- 8. Create single-year scoring plot ----
  return(create_single_year_plot(
    plot_df = plot_df,
    donor_name = donor_name,
    year_single = year_single,
    verbose = verbose,
    donor_metrics = donor_metrics,
    scored = scored
  ))
}

# Helper function for multi-year trajectory plot
create_multi_year_plot <- function(df, years_to_plot, ref_year, top_donors, donor_name,
                                   ctr_name, weight_by, wb_weights, top_n_display) {
  
  # Aggregate by donor and year
  df_year <- df |>
    dplyr::filter(.data$transaction_provider_org %in% .env$top_donors) |>
    dplyr::group_by(.data$transaction_provider_org, .data$year_tx) |>
    dplyr::summarise(total_funding = sum(.data$tx_value, na.rm = TRUE), .groups = "drop")
  
  # Apply weighting if requested
  if (weight_by != "none" && !is.null(wb_weights)) {
    df_year <- df_year |>
      dplyr::left_join(
        wb_weights |> dplyr::rename(year_tx = .data$year_wb),
        by = c("transaction_provider_org", "year_tx")
      ) |>
      dplyr::filter(!(is.na(.data$population) & weight_by %in% c("population", "population_gdp")),
                    !(is.na(.data$gdp) & weight_by %in% c("gdp", "population_gdp"))) |>
      dplyr::mutate(
        metric_value = compute_weighted_metric(
          .data$total_funding,
          .data$population,
          .data$gdp,
          weight_by
        )
      )
  } else {
    df_year <- df_year |> dplyr::mutate(metric_value = .data$total_funding)
  }
  
  # Order donors by reference year performance
  ref_order <- df_year |>
    dplyr::filter(.data$year_tx == .env$ref_year) |>
    dplyr::arrange(.data$metric_value) |>
    dplyr::pull(.data$transaction_provider_org) |>
    as.character()
  
  df_year <- df_year |>
    dplyr::mutate(
      donor = factor(.data$transaction_provider_org, levels = ref_order),
      year_f = factor(.data$year_tx, levels = sort(unique(.data$year_tx))),
      highlight = if (is.null(donor_name)) {
        "No"
      } else {
        ifelse(.data$transaction_provider_org == donor_name, "Yes", "No")
      }
    )
  
  # Calculate ranges for connecting lines
  df_ranges <- df_year |>
    dplyr::group_by(.data$donor) |>
    dplyr::summarise(
      xmin = min(.data$metric_value, na.rm = TRUE),
      xmax = max(.data$metric_value, na.rm = TRUE),
      .groups = "drop"
    )
  
  # Prepare titles
  title <- paste0(
    "Donor ranking trajectory (", min(years_to_plot), "–", max(years_to_plot), ")",
    if (!is.null(ctr_name)) paste0(" — ", paste(ctr_name, collapse = ", ")) else ""
  )
  
  subtitle <- paste0(
    "Top ", top_n_display, " donors (selected by ", ref_year, "). ",
    "Points are annual values; color indicates year. ",
    if (weight_by != "none") paste0("Weighted by ", weight_by, ". ")
  )
  
  # Create plot
  p <- ggplot2::ggplot(df_year, ggplot2::aes(y = .data$donor, x = .data$metric_value)) +
    ggplot2::geom_segment(
      data = df_ranges,
      ggplot2::aes(y = .data$donor, yend = .data$donor, x = .data$xmin, xend = .data$xmax),
      linewidth = 1,
      color = "#B9C2CB"
    ) +
    ggplot2::geom_point(ggplot2::aes(color = .data$year_f), size = 3.8) +
    ggplot2::scale_color_brewer(palette = "Set1", name = "Year") +
    ggplot2::scale_x_continuous(
      labels = scales::label_number(scale_cut = scales::cut_short_scale())
    ) +
    unhcrthemes::theme_unhcr(
      grid = "X",
      axis = "Y",
      axis_title = FALSE,
      font_size = 20
    ) +
    ggplot2::labs(
      title = title,
      subtitle = subtitle,
      x = "Funding amount",
      y = NULL,
      caption = "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI)"
    )
  
  # Highlight specific donor if requested
  if (!is.null(donor_name)) {
    p <- p + ggplot2::geom_point(
      data = dplyr::filter(df_year, .data$highlight == "Yes"),
      ggplot2::aes(color = .data$year_f),
      size = 5.2
    )
  }
  
  return(p)
}

# Helper function for weighted metric calculation
compute_weighted_metric <- function(total, population, gdp, method) {
  switch(method,
    "population" = total / population,
    "gdp" = total / gdp,
    "population_gdp" = total / (population * gdp),
    total  # "none"
  )
}

# Helper function for single-year scoring plot
create_single_year_plot <- function(plot_df, donor_name, year_single, verbose,
                                    donor_metrics, scored) {
  
  # Check if we have a donor to highlight
  has_focus <- !is.null(donor_name) && donor_name %in% plot_df$transaction_provider_org
  
  # Split data for plotting
  if (has_focus) {
    df_focus <- plot_df |> dplyr::filter(.data$transaction_provider_org == .env$donor_name)
    df_others <- plot_df |> dplyr::filter(.data$transaction_provider_org != .env$donor_name)
  } else {
    df_focus <- NULL
    df_others <- NULL
  }
  
  # Define aesthetics
  col_all <- scales::alpha("#8E99A4", 0.35)  # Light grey, semi-transparent
  col_focus <- "#0072BC"                     # UNHCR blue
  size_all <- 3.0
  size_focus <- 4.6
  
  # Base plot
  p <- ggplot2::ggplot(mapping = ggplot2::aes(x = .data$metric, y = .data$score))
  
  if (has_focus) {
    # Plot other donors in grey
    p <- p + ggplot2::geom_point(
      data = df_others,
      color = col_all,
      size = size_all,
      position = ggplot2::position_jitter(width = 0.08, height = 0, seed = 42),
      na.rm = TRUE
    )
    
    # Plot highlighted donor in blue
    p <- p + ggplot2::geom_point(
      data = df_focus,
      color = col_focus,
      size = size_focus,
      na.rm = TRUE
    )
    
    # Add rank labels for highlighted donor
    if (requireNamespace("ggrepel", quietly = TRUE)) {
      p <- p + ggrepel::geom_text_repel(
        data = dplyr::filter(df_focus, !is.na(.data$rk_lab)),
        ggplot2::aes(label = .data$rk_lab),
        color = "black",
        size = 10,
        direction = "y",
        box.padding = 0.15,
        point.padding = 0.25,
        segment.color = "grey60",
        segment.size = 0.3,
        min.segment.length = 0,
        nudge_y = 4.5,
        na.rm = TRUE
      )
    } else {
      p <- p + ggplot2::geom_text(
        data = dplyr::filter(df_focus, !is.na(.data$rk_lab)),
        ggplot2::aes(label = .data$rk_lab),
        color = col_focus,
        size = 4.0,
        vjust = -0.7,
        na.rm = TRUE
      )
    }
  } else {
    # Plot all donors in grey
    p <- p + ggplot2::geom_point(
      data = plot_df,
      color = col_all,
      size = size_all,
      position = ggplot2::position_jitter(width = 0.08, height = 0, seed = 42),
      na.rm = TRUE
    )
  }
  
  # Add plot elements
  p <- p +
    ggplot2::scale_y_continuous(
      limits = c(0, 100),
      breaks = seq(0, 100, by = 20)
    ) +
    ggplot2::labs(
      title = paste0(
        "Donor scoring (", year_single, ") — ",
        if (has_focus) donor_name else "All donors"
      ),
      subtitle = paste(
        "Scores: min–max across donors per metric.",
        if (has_focus) "Blue = selected donor; label shows rank within each metric."
      ),
      x = "Score type",
      y = "Score (0–100)",
      caption = "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI)"
    ) +
    unhcrthemes::theme_unhcr(
      grid = "Y",
      axis = "X",
      axis_title = FALSE,
      font_size = 20
    ) +
    ggplot2::theme(legend.position = "none")
  
  # Print verbose output if requested
  if (verbose) {
    message("Single-year scoring plot created for year: ", year_single)
    message("Total donors included: ", nrow(donor_metrics))
    message("Donors with GDP data: ", sum(!is.na(scored$usd_per_gdp)))
    if (!has_focus) {
      message("Tip: Use donor_name parameter to highlight a specific donor.")
    }
  }
  
  return(p)
}
