# WARNING - Generated by {fusen} from dev/dev_donor_focus.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot donor transaction description
#'
#' @description
#' Creates a visualization showing the breakdown of a donor's funding by transaction description.
#' If only `by` is NULL, it returns a bar chart of transaction descriptions.
#' If `by` is provided, it returns a heatmap cross-tabulation of transaction description vs the specified dimension.
#'
#' @param donor_name Character. The name of the donor to plot.
#' @param by Optional character. A second category to create a heatmap with transaction description.
#'   One of "unhcr_region", "year", "earmarking_name", or "ctr_name".
#' @param year Optional numeric/integer vector. Year(s) to filter on.
#' @param programme_lab Optional character vector. Filter for programme name.
#' @param iati_identifier_ops Optional character vector. Filter for operation ID.
#' @param ctr_name Optional character vector. Filter for country name.
#' @param top_n Integer. The number of top transaction descriptions to show.
#'
#' @return A ggplot object.
#'
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import forcats
#' @import stringr
#' @import unhcrthemes
#'
#' @export
#' @examples
#'
#' # Show top 10 transaction descriptions for a donor
#' show_donor_transaction_desc(
#'   donor_name = "Private donors", 
#'   year = 2024,
#'   top_n = 10
#' )
#'
#' # Show top 10 transaction descriptions for a donor
#' show_donor_transaction_desc(
#'   donor_name = "Private donors", 
#'   year = 2022:2025,
#'   top_n = 10
#' )
#'
#' # Show earmarking breakdown with proper color coding
#' show_donor_transaction_desc(
#'   donor_name = "Private donors",
#'   by = "earmarking_name",
#'   year = 2024,
#'   top_n = 4  # Shows all 4 earmarking types
#' )
#'
#' # Show funding by region
#' show_donor_transaction_desc(
#'   donor_name = "Private donors",
#'   by = "unhcr_region",
#'   year = 2025,
#'   top_n = 8
#' )
#'
#'
show_donor_transaction_desc <- function(donor_name,
                                        by = NULL,
                                        year = NULL,
                                        programme_lab = NULL,
                                        iati_identifier_ops = NULL,
                                        ctr_name = NULL,
                                        top_n = 10) {

  # ---- 0) Validate inputs ----
  allowed_by <- c("unhcr_region", "year", "earmarking_name", "ctr_name")
  
  if (!is.null(by)) {
    if (!by %in% allowed_by) {
      stop("`by` must be one of: ", paste(allowed_by, collapse = ", "))
    }
  }
  
  if (!is.numeric(top_n) || length(top_n) != 1 || top_n < 1) {
    stop("`top_n` must be a single integer >= 1.")
  }

  # Avoid name collisions with columns (year arg vs year column, etc.)
  year_filter      <- year
  programme_filter <- programme_lab
  ops_filter       <- iati_identifier_ops
  country_filter   <- ctr_name

  # ---- 1) Load & filter data ----
  df <- iati::dataTransaction |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier") |>
    dplyr::filter(
      .data$transaction_provider_org == donor_name,
      .data$transaction_type_name == "Incoming Commitment"
    )

  if (!is.null(year_filter)) {
    df <- df |> dplyr::filter(.data$year %in% .env$year_filter)
  }
  if (!is.null(programme_filter)) {
    df <- df |> dplyr::filter(.data$programme_lab %in% .env$programme_filter)
  }
  if (!is.null(ops_filter)) {
    df <- df |> dplyr::filter(.data$iati_identifier_ops %in% .env$ops_filter)
  }
  if (!is.null(country_filter)) {
    df <- df |> dplyr::filter(.data$ctr_name %in% .env$country_filter)
  }

  # ---- 2) Clean unhcr_region data ----
  # Replace empty or NA unhcr_region with "global/HQ"
  if (!is.null(by) && by == "unhcr_region") {
    df <- df |>
      dplyr::mutate(
        unhcr_region = dplyr::case_when(
          is.na(.data$unhcr_region) ~ "global/HQ",
          trimws(.data$unhcr_region) == "" ~ "global/HQ",
          TRUE ~ .data$unhcr_region
        )
      )
  }

  # ---- 3) Determine grouping columns ----
  # Always include transaction_description, and add 'by' if provided
  col_vars <- c("transaction_description", by)
  col_vars <- col_vars[!is.null(col_vars)]

  # ---- 4) Aggregate (base) ----
  show_data <- df |>
    dplyr::filter(dplyr::if_all(dplyr::all_of(col_vars), ~ !is.na(.))) |>
    dplyr::group_by(dplyr::across(dplyr::all_of(col_vars))) |>
    dplyr::summarise(
      total_funding = sum(.data$transaction_value_USD, na.rm = TRUE),
      .groups = "drop"
    )

  # ---- 5) Lumping helper (Top N + Other) ----
  lump_transaction_desc <- function(data, n) {
    data |>
      dplyr::mutate(
        transaction_description = forcats::fct_lump_n(
          forcats::fct_reorder(
            as.factor(.data$transaction_description),
            total_funding,
            .fun = sum,
            .desc = TRUE
          ),
          n = n,
          w = total_funding,
          other_level = "Other"
        )
      )
  }
  
  # For "by" dimension handling
  process_by_dimension <- function(data, by_var) {
    if (is.null(by_var)) return(data)
    
    if (by_var == "earmarking_name") {
      # Preserve all 4 earmarking categories
      data <- data |>
        dplyr::mutate(
          earmarking_name = factor(.data$earmarking_name,
            levels = c("Tightly Earmarked", "Earmarked", "Softly Earmarked", "Unearmarked")
          )
        )
    } else if (by_var == "year") {
      # Order years chronologically
      data <- data |>
        dplyr::mutate(
          year = factor(.data$year, levels = sort(unique(.data$year)))
        )
    } else if (by_var %in% c("unhcr_region", "ctr_name")) {
      # For region and country, show top categories based on data
      # These will be ordered by total in the heatmap
      data <- data
    }
    
    return(data)
  }

  # Apply lumping to transaction description (always)
  show_data <- lump_transaction_desc(show_data, top_n)
  
  # Process the 'by' dimension if provided
  show_data <- process_by_dimension(show_data, by)
  
  # Re-aggregate after lumping/processing
  show_data <- show_data |>
    dplyr::group_by(dplyr::across(dplyr::all_of(col_vars))) |>
    dplyr::summarise(total_funding = sum(.data$total_funding, na.rm = TRUE), .groups = "drop")

  # ---- 6) Calculate total funding for title ----
  total_funding_amount <- sum(show_data$total_funding, na.rm = TRUE)
  formatted_total <- scales::label_number(
    scale_cut = scales::cut_short_scale(),
    accuracy = 0.1
  )(total_funding_amount)

  # ---- 7) Create title ----
  if (!is.null(year_filter) && length(year_filter) == 1) {
    title <- paste("Transaction Description for", donor_name, "in", year_filter, "| Total:", formatted_total, "USD")
  } else if (!is.null(year_filter) && length(year_filter) > 1) {
    years_range <- paste(min(year_filter), "-", max(year_filter))
    title <- paste("Transaction Description for", donor_name, years_range, "| Total:", formatted_total, "USD")
  } else {
    title <- paste("Transaction Description for", donor_name, "| Total:", formatted_total, "USD")
  }

  # ---- 8) Create subtitle ----
  subtitle_text <- if (is.null(by)) {
    if (!is.null(country_filter)) {
      paste0("In ", paste(country_filter, collapse = ", "))
    } else if (!is.null(programme_filter)) {
      paste0("For programme(s): ", paste(programme_filter, collapse = ", "))
    } else {
      paste0("Top ", top_n, " transaction descriptions")
    }
  } else {
    paste("Transaction description by", stringr::str_to_title(gsub("_", " ", by)))
  }

  # ---- 9) Plotting ----
  if (is.null(by)) {
    # BAR CHART - Transaction descriptions only
    
    # Prepare data for bar chart (summarize and order)
    bar_data <- show_data |>
      dplyr::group_by(.data$transaction_description) |>
      dplyr::summarise(total_funding = sum(.data$total_funding, na.rm = TRUE), .groups = "drop") |>
      dplyr::mutate(
        transaction_description = forcats::fct_reorder(.data$transaction_description, .data$total_funding, .desc = FALSE)
      )
    
    p <- ggplot2::ggplot(
      bar_data,
      ggplot2::aes(x = .data$transaction_description, y = .data$total_funding)
    ) +
      ggplot2::geom_col(fill = "#0072BC") +
      ggplot2::coord_flip() +
      ggplot2::scale_y_continuous(
        labels = scales::label_number(scale_cut = scales::cut_short_scale())
      ) +
      unhcrthemes::theme_unhcr(grid = "X", axis = "y", axis_title = "X", font_size = 18) +
      ggplot2::labs(
        title = title,
        subtitle = subtitle_text,
        x = "Transaction Description",
        y = "Total Funding (USD)",
        caption = "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI)"
      )

  } else {
    # HEATMAP - Transaction description by another dimension
    
    # Determine axis labels
    x_label <- if (by == "ctr_name") "Country" else stringr::str_to_title(gsub("_", " ", by))
    y_label <- "Transaction Description"
    
    # Order transaction descriptions by total funding (highest at top)
    heatmap_data <- show_data |>
      dplyr::group_by(.data$transaction_description) |>
      dplyr::mutate(desc_total = sum(.data$total_funding)) |>
      dplyr::ungroup() |>
      dplyr::mutate(
        transaction_description = forcats::fct_reorder(.data$transaction_description, .data$desc_total, .desc = TRUE)
      )
    
    # For year dimension, ensure proper ordering on x-axis
    if (by == "year") {
      heatmap_data <- heatmap_data |>
        dplyr::mutate(
          !!rlang::sym(by) := factor(!!rlang::sym(by), levels = sort(unique(!!rlang::sym(by))))
        )
    }
    
    p <- ggplot2::ggplot(
      heatmap_data,
      ggplot2::aes(
        x = !!rlang::sym(by),
        y = .data$transaction_description,
        fill = .data$total_funding
      )
    ) +
      ggplot2::geom_tile(color = "white", linewidth = 0.5) +
      ggplot2::scale_fill_gradient(
        low = "#DCEEF9",
        high = "#0072BC",
        labels = scales::label_number(scale_cut = scales::cut_short_scale())
      ) +
      unhcrthemes::theme_unhcr(grid = FALSE, axis = "xy", font_size = 18) +
      ggplot2::theme(
        axis.text.x = ggplot2::element_text(angle = 45, vjust = 1, hjust = 1)
      ) +
      ggplot2::labs(
        title = title,
        subtitle = subtitle_text,
        x = x_label,
        y = y_label,
        fill = "Funding (USD)",
        caption = "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI)"
      )
  }

  p
}
