# WARNING - Generated by {fusen} from dev/dev_donor_focus.Rmd: do not edit by hand # nolint: line_length_linter.


#' Plot donor geographic priority shift over time (alluvial, CVD-safe colors + correct labels)
#'
#' @param donor_name The donor to highlight.
#' @param top_n_countries Number of top recipient countries to display.
#' @param start_year Optional start year.
#' @param end_year Optional end year.
#' @param verbose Print diagnostic messages.
#' 
#' @import ggplot2
#' @import dplyr
#' @importFrom ggalluvial geom_alluvium
#'
#' @return A fully labeled ggalluvial plot.
#' @export
#' @examples
#' # Example usage: 
#' show_donor_geographic_priority_shift(
#'    donor_name = "Private donors", 
#'    top_n_countries = 7,
#'    start_year = 2022,
#'    end_year = 2025
#'  )
show_donor_geographic_priority_shift <- function(
  donor_name,
  top_n_countries = 5,
  start_year = NULL,
  end_year = NULL,
  verbose = TRUE
) {

  # ---- Required packages ----
  if (!requireNamespace("ggalluvial", quietly = TRUE)) {
    stop("Package `ggalluvial` is required. Install with install.packages('ggalluvial').")
  }
  has_ggrepel <- requireNamespace("ggrepel", quietly = TRUE)

  # ---- Load data ----
  data_activity    <- iati::dataActivity
  data_transaction <- iati::dataTransaction

  # ---- Prepare data ----
  df_plot <- data_transaction |>
    dplyr::inner_join(
      data_activity |> dplyr::select(iati_identifier, ctr_name),
      by = "iati_identifier"
    ) |>
    dplyr::mutate(
      year = lubridate::year(lubridate::ymd(transaction_date)),
      transaction_value = as.numeric(transaction_value)
    ) |>
    dplyr::filter(
      !is.na(year),
      !is.na(transaction_value_USD),
      !is.na(ctr_name)
    ) |>
    dplyr::group_by(transaction_provider_org, year, ctr_name) |>
    dplyr::summarise(
      total_funding = sum(transaction_value_USD, na.rm = TRUE),
      .groups = "drop"
    )

  # ---- Year filters ----
  if (!is.null(start_year)) df_plot <- dplyr::filter(df_plot, year >= start_year)
  if (!is.null(end_year))   df_plot <- dplyr::filter(df_plot, year <= end_year)

  # ---- Donor subset ----
  df_donor <- df_plot |>
    dplyr::filter(transaction_provider_org == donor_name) |>
    dplyr::group_by(year) |>
    dplyr::mutate(total_year_funding = sum(total_funding)) |>
    dplyr::ungroup() |>
    dplyr::filter(total_year_funding > 0) |>
    dplyr::mutate(
      funding_pct = total_funding / total_year_funding,
      recipient_country = forcats::fct_reorder(
        ctr_name, total_funding, .fun = sum, .desc = TRUE
      )
    )

  # ---- Identify Top-N Countries ----
  top_countries <- df_donor |>
    dplyr::group_by(recipient_country) |>
    dplyr::summarise(tot = sum(total_funding)) |>
    dplyr::arrange(desc(tot)) |>
    utils::head(top_n_countries) |>
    dplyr::pull(recipient_country) |>
    as.character()

  # ---- Collapse others ----
  df_show <- df_donor |>
    dplyr::mutate(
      country_group = ifelse(
        recipient_country %in% top_countries,
        as.character(recipient_country),
        "Other Countries"
      )
    ) |>
    dplyr::group_by(year, country_group) |>
    dplyr::summarise(funding_pct = sum(funding_pct), .groups = "drop") |>
    dplyr::ungroup()

  # ---- Factor ordering ----
  level_order <- c(top_countries, "Other Countries")

  df_show <- df_show |>
    dplyr::mutate(
      country_group = factor(country_group, levels = level_order),
      year_fct = factor(year, levels = sort(unique(year)))
    )

  # ---- CVD-safe palette ----
  get_cvd_palette <- function(n) {
    okabe_ito <- c(
      "#0072B2", "#E69F00", "#009E73", "#D55E00",
      "#CC79A7", "#56B4E9", "#F0E442", "#000000"
    )
    if (n <= length(okabe_ito)) okabe_ito[seq_len(n)]
    else if (requireNamespace("viridisLite", quietly = TRUE))
      viridisLite::viridis(n)
    else rep(okabe_ito, length.out = n)
  }

  top_cols <- get_cvd_palette(length(top_countries))
  grey_other <- "#B3B3B3"

  fill_values <- stats::setNames(
    c(top_cols, grey_other),
    c(top_countries, "Other Countries")
  )

  # ---- Build alluvial plot (NO labels yet) ----
  p <- ggplot2::ggplot(
    df_show,
    ggplot2::aes(
      x = year_fct,
      y = funding_pct,
      alluvium = country_group,
      stratum = country_group,
      fill = country_group
    )
  ) +
    ggalluvial::geom_alluvium(
      width = 0.25,
      knot.pos = 0.4,
      aes.bind = "flows",
      decreasing = FALSE,
      alpha = 0.9
    ) +
    ggplot2::scale_fill_manual(values = fill_values) +
    ggplot2::scale_y_continuous(labels = scales::percent) +
    ggplot2::scale_x_discrete(expand = ggplot2::expansion(add = c(0.05, 0.05))) +
    ggplot2::labs(
      title = paste0("Disbursements Shift for ", donor_name),
      #subtitle = " ",
      x = "",
      y = ""
    ) +
    unhcrthemes::theme_unhcr( legend = TRUE,
                              legend_title = FALSE,
                             font_size = 20) +

    ggplot2::coord_cartesian(clip = "off")

  # ---- Extract TRUE ymax/ymin from plotted polygons ----
  pb <- ggplot_build(p)
  alluvium_df <- pb$data[[1]]

  last_year <- max(df_show$year)
  last_year_fct <- as.character(last_year)

  last_x_id <- which(levels(df_show$year_fct) == last_year_fct)

  ribbon_bounds <- alluvium_df |>
    dplyr::filter(x == last_x_id) |>
    dplyr::group_by(fill) |>
    dplyr::summarise(
      ymin = min(y),
      ymax = max(y),
      y_mid = (ymin + ymax) / 2,
      .groups = "drop"
    )

  labels_df <- ribbon_bounds |>
    dplyr::mutate(
      country_group = names(fill_values)[match(fill, fill_values)],
      label = ifelse(country_group == "Other Countries", "Other", country_group),
      year_fct = last_year_fct
    )

  # # ---- Add Direct Labels ----
  # if (has_ggrepel) {
  #   p <- p +
  #     ggrepel::geom_label_repel(
  #       data = labels_df,
  #       ggplot2::aes(x = year_fct, y = y_mid, label = label),
  #       inherit.aes = FALSE,
  #       nudge_x = 0.4,
  #       hjust = 0,
  #       direction = "y",
  #       segment.color = "grey60",
  #       size = 7,
  #       max.overlaps = Inf
  #     )
  # } else {
  #   p <- p +
  #     ggplot2::geom_text(
  #       data = labels_df,
  #       ggplot2::aes(x = year_fct, y = y_mid, label = label),
  #       inherit.aes = FALSE,
  #       hjust = 0,
  #       nudge_x = 0.25,
  #       size = 6.5
  #     )
  # }

  return(p)
}

