# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand # nolint: line_length_linter.

#' Show a flow diagram of implementing partners
#'
#' @description This function creates a Sankey diagram to visualize the relationships
#' between implementing partner roles, their organization types, and their names.
#'
#' @param year A numeric value for the year.
#' @param ctr_name A character vector for the country name.
#' @param programme_lab A character vector for the programme name.
#' @param iati_identifier_ops A character vector for the operation ID.
#' @param top_n The number of top implementing partners to show.
#'
#' @import ggplot2
#' @import dplyr
#' @import ggsankey
#' @import unhcrthemes
#'
#' @export
#' @examples
#' show_implementing_partners_flow(year = 2025, ctr_name = "Brazil")
show_implementing_partners_flow <- function(year,
                                            ctr_name = NULL,
                                            programme_lab = NULL,
                                            iati_identifier_ops = NULL,
                                            top_n = 15) {

  df <- iati::dataParticipating_org |>
    dplyr::left_join(iati::dataActivity, by = "iati_identifier")

  # Filtering
  if (!is.null(programme_lab)) {
    df <- df |> dplyr::filter(programmme_lab == {{programme_lab}} & year == {{year}})
  } else if (!is.null(iati_identifier_ops)) {
    df <- df |> dplyr::filter(iati_identifier_ops == {{iati_identifier_ops}} & year == {{year}})
  } else if (!is.null(ctr_name)) {
    df <- df |> dplyr::filter(ctr_name == {{ctr_name}} & year == {{year}})
  }

  df_flow <- df |>
    dplyr::filter(participating_org_role_name %in% c("Implementing", "Extending")) |>
    dplyr::count(participating_org_role_name, participating_org_type_name, participating_org_eng, name = "count") |>
    dplyr::mutate(participating_org_eng = forcats::fct_lump_n(
      participating_org_eng, n = top_n, w = count, other_level = "Other Partners"
    )) |>
    dplyr::group_by(participating_org_role_name, participating_org_type_name, participating_org_eng) |>
    dplyr::summarise(value = sum(count)) |>
    dplyr::ungroup() |>
    ggsankey::make_long(participating_org_role_name, participating_org_type_name, participating_org_eng, value = value)

  ggplot2::ggplot(df_flow, ggplot2::aes(x = x, next_x = next_x, node = node, next_node = next_node,
                     fill = factor(node), value = value, label = node)) +
    ggsankey::geom_sankey(flow.alpha = 0.6) +
    ggsankey::geom_sankey_label(size = 3, color = "black", fill = "white", hjust = -0.1) +
    unhcrthemes::theme_unhcr(grid = FALSE, axis = FALSE, axis_text = FALSE, legend = FALSE) +
    ggplot2::scale_fill_viridis_d(option = "viridis") +
    ggplot2::labs(title = "Flow of Implementing Partnerships",
         subtitle = paste0("For ", ctr_name %||% programme_lab %||% iati_identifier_ops, " in ", year),
         caption = "Source: IATI Data")
}
