# WARNING - Generated by {fusen} from dev/Data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' xml_child_attr_by_name
#' 
#' Extracts an attribute value from a child node within the XML.
#' 
#' @param i An XML object 
#' @param node_name The name of the target node.
#' @param attr_name  The name of the attribute to extract.
#' @param attr_position  An optional argument specifying the position of the desired attribute
#'  (default is 1).
#' 
#' @import xml2
#' @import rlang
#' @import dplyr
#' 
#' @return string
#' 
#' @noRd
#' @examples
#' #xml_child_attr_by_name()
xml_child_attr_by_name <-   function(i, node_name, attr_name, attr_position = 1L) {
    x <- tryCatch(
      i |> 
        # Find all child nodes with the specified node_name.
        xml2::xml_find_all(node_name) |> 
        # Retrieve the attribute value specified by attr_name.
        xml_attr(attr_name) |> 
        dplyr::nth(attr_position),
      error = function(e) {
        NA_character_
      }
    )
    
      # Handle any errors (return NA_character_ if necessary).
    if (rlang::is_empty(x) == TRUE) {
      x <- NA_character_
    } else {
      x
    }
    return(x)
  }
