# WARNING - Generated by {fusen} from dev/Data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' xml_attr_by_name
#' 
#' This function is designed to extract an attribute value from a specific XML node.
#' 
#' @param i An XML object
#' @param parent_name The name of the parent node.
#' @param node_name The name of the target node.
#' @param attr_name  The name of the attribute to extract.
#' @param attr_position  An optional argument specifying the position of the desired attribute
#'  (default is 1).
#' 
#' @import xml2
#' @import rlang
#' @import dplyr
#' 
#' @return string
#' 
#' @noRd
#' @examples
#' #xml_attr_by_name()
xml_attr_by_name <-
  function(i, parent_name, node_name, attr_name, attr_position = 1L) {
    # First, it finds all nodes with the name specified by parent_name using xml2::xml_find_all.
    i =  i |> 
      xml2::xml_find_all(parent_name)
    
    # Then, it identifies the position of the desired node_name within those nodes.
    x <- tryCatch(
      i[i |>
          xml_name() |>
          (\(x) which(x == node_name))() |> 
          nth(attr_position)] |>
        # Next, it retrieves the attribute value specified by attr_name from that node.
        xml_attr(attr_name),
    
      error = function(e) {
        NA_character_
      }
    )
      # If an error occurs during this process (e.g., if the node or attribute is not found), it returns NA_character_.
    if (rlang::is_empty(x) == TRUE) {
      x <- NA_character_
    } else {
      x
    }
    return(x)
  }
