# WARNING - Generated by {fusen} from dev/Data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' xml_text_by_name
#' 
#'  extracts the text content from a specific XML node.
#'  
#' @param i An XML object
#' @param parent_name The name of the parent node.
#' @param node_name The name of the target node.
#' @param attr_name  The name of the attribute to extract.
#' @param attr_position  An optional argument specifying the position of the desired attribute
#'     (default is 1).
#' 
#' @import xml2
#' @import rlang
#' @import dplyr
#' 
#' @return string
#' 
#' @noRd
#' @examples
#' #xml_text_by_name()
xml_text_by_name <- function(i, parent_name, node_name, attr_position = 1L) {
    i =  i |> 
      xml2::xml_find_all(parent_name)
    
    x <- tryCatch(
      i[i |> xml_name() |> (\(x) which(x == node_name))()|> 
          nth(attr_position)] |> xml_text(),
      error = function(e) {
        NA_character_
      }
    )
    
    if (rlang::is_empty(x) == TRUE) {
      x <- NA_character_
    } else {
      x
    }
    return(x)
  }

