# WARNING - Generated by {fusen} from dev/Data_reshape.Rmd: do not edit by hand # nolint: line_length_linter.

#' xml_text_by_lang
#' 
#' @param i An XML object
#' @param parent_name The name of the parent node.
#' @param set_xml_name The name of the target node for language-specific content.
#' @param language   The desired language.
#' @param attr_position  An optional argument specifying the position of the desired attribute
#'     (default is 1).
#' 
#' @import xml2
#' @import rlang
#' @import dplyr
#' 
#' @return string
#' 
#' @noRd
#' @examples
#' #xml_text_by_lang()
xml_text_by_lang <- function(i, 
                             parent_name, 
                             set_xml_name, 
                             language, 
                             attr_position = 1L) {
    # Find all nodes with the specified parent_name.
    i =  i |> 
      xml2::xml_find_all(parent_name)
    
    # Identify the position of the desired node_name.
    x <- tryCatch(
      (i |> xml2::xml_find_all(set_xml_name))[grep(language, i |>
                                               xml_contents() |>
                                               xml_attrs())|> 
                                          nth(attr_position)] |> 
        # Retrieve the text content from that node.
        xml_text(),
      error = function(e) {
        NA_character_
      }
    )
    # Handle errors (return NA_character_ if needed).
    if (rlang::is_empty(x) == TRUE) {
      x <- NA_character_
    } else {
      x
    }
    # Return the extracted text content.
    return(x)
  }
